-- Canonical product identity layer.
-- Multiple retailer/market barcodes can point to one physical product identity.
-- Example: two GTINs for the same Pepsi 330 ml can share one canonical_product_id.

create table if not exists canonical_products (
    id bigint generated by default as identity primary key,
    canonical_name_ar text,
    canonical_name_en text,
    brand text,
    variant text,
    net_content_value numeric,
    net_content_unit text,
    pack_count integer not null default 1 check (pack_count > 0),
    image_url text,
    product_info jsonb,
    identity_key text unique,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists product_aliases (
    barcode text primary key references products(barcode) on delete cascade,
    canonical_product_id bigint not null references canonical_products(id) on delete cascade,
    match_method text not null default 'single_barcode',
    match_confidence double precision not null default 1.0 check (match_confidence between 0 and 1),
    verified boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists product_aliases_canonical_idx
    on product_aliases (canonical_product_id, barcode);

-- Creates/updates product metadata and guarantees that every barcode belongs to a canonical identity.
-- p_identity_key must only be supplied by the ingestion matcher when brand + variant + size + pack
-- are sufficiently certain. If absent, the barcode gets an isolated identity and cannot be merged by accident.
create or replace function upsert_product_metadata(
    p_barcode text,
    p_name_ar text default null,
    p_name_en text default null,
    p_brand text default null,
    p_image_url text default null,
    p_gs1_verified boolean default false,
    p_identity_key text default null,
    p_variant text default null,
    p_net_content_value numeric default null,
    p_net_content_unit text default null,
    p_pack_count integer default 1,
    p_match_confidence double precision default 1.0,
    p_match_method text default 'barcode'
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_canonical_id bigint;
begin
    if p_barcode !~ '^[0-9]{8,14}$' then
        raise exception 'Invalid barcode: %', p_barcode;
    end if;

    insert into products (barcode, name_ar, name_en, brand, image_url, gs1_verified, updated_at)
    values (p_barcode, p_name_ar, p_name_en, p_brand, p_image_url, p_gs1_verified, now())
    on conflict (barcode) do update
    set name_ar = coalesce(excluded.name_ar, products.name_ar),
        name_en = coalesce(excluded.name_en, products.name_en),
        brand = coalesce(excluded.brand, products.brand),
        image_url = coalesce(excluded.image_url, products.image_url),
        gs1_verified = products.gs1_verified or excluded.gs1_verified,
        updated_at = now();

    select canonical_product_id into v_canonical_id
    from product_aliases
    where barcode = p_barcode;

    if v_canonical_id is not null then
        update canonical_products
        set canonical_name_ar = coalesce(canonical_name_ar, p_name_ar),
            canonical_name_en = coalesce(canonical_name_en, p_name_en),
            brand = coalesce(brand, p_brand),
            variant = coalesce(variant, p_variant),
            net_content_value = coalesce(net_content_value, p_net_content_value),
            net_content_unit = coalesce(net_content_unit, p_net_content_unit),
            pack_count = greatest(pack_count, coalesce(p_pack_count, 1)),
            image_url = coalesce(image_url, p_image_url),
            updated_at = now()
        where id = v_canonical_id;
        return v_canonical_id;
    end if;

    if nullif(trim(coalesce(p_identity_key, '')), '') is not null then
        select id into v_canonical_id
        from canonical_products
        where identity_key = p_identity_key;
    end if;

    if v_canonical_id is null then
        insert into canonical_products (
            canonical_name_ar, canonical_name_en, brand, variant,
            net_content_value, net_content_unit, pack_count, image_url, identity_key
        ) values (
            p_name_ar, p_name_en, p_brand, p_variant,
            p_net_content_value, p_net_content_unit, greatest(coalesce(p_pack_count, 1), 1),
            p_image_url,
            nullif(trim(coalesce(p_identity_key, '')), '')
        )
        returning id into v_canonical_id;
    end if;

    insert into product_aliases (
        barcode, canonical_product_id, match_method, match_confidence, verified, updated_at
    ) values (
        p_barcode,
        v_canonical_id,
        coalesce(nullif(p_match_method, ''), 'barcode'),
        greatest(0.0, least(coalesce(p_match_confidence, 1.0), 1.0)),
        p_gs1_verified,
        now()
    )
    on conflict (barcode) do update
    set canonical_product_id = excluded.canonical_product_id,
        match_method = excluded.match_method,
        match_confidence = excluded.match_confidence,
        verified = product_aliases.verified or excluded.verified,
        updated_at = now();

    return v_canonical_id;
end;
$$;

-- Explicit correction/curation path. Use this for verified alternate GTINs or when the
-- conservative automatic matcher refuses to merge two equivalent products.
create or replace function link_product_alias(
    p_barcode text,
    p_canonical_product_id bigint,
    p_method text default 'manual_verified',
    p_confidence double precision default 1.0,
    p_verified boolean default true
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    if not exists (select 1 from products where barcode = p_barcode) then
        raise exception 'Unknown barcode: %', p_barcode;
    end if;
    if not exists (select 1 from canonical_products where id = p_canonical_product_id) then
        raise exception 'Unknown canonical product: %', p_canonical_product_id;
    end if;

    insert into product_aliases (
        barcode, canonical_product_id, match_method, match_confidence, verified, updated_at
    ) values (
        p_barcode, p_canonical_product_id, p_method,
        greatest(0.0, least(p_confidence, 1.0)), p_verified, now()
    )
    on conflict (barcode) do update
    set canonical_product_id = excluded.canonical_product_id,
        match_method = excluded.match_method,
        match_confidence = excluded.match_confidence,
        verified = excluded.verified,
        updated_at = now();
end;
$$;

-- Backfill existing rows safely: until matched, each historical barcode gets its own identity.
do $$
declare
    r record;
    v_id bigint;
begin
    for r in
        select p.*
        from products p
        left join product_aliases pa on pa.barcode = p.barcode
        where pa.barcode is null
    loop
        insert into canonical_products (
            canonical_name_ar, canonical_name_en, brand, image_url
        ) values (r.name_ar, r.name_en, r.brand, r.image_url)
        returning id into v_id;

        insert into product_aliases (
            barcode, canonical_product_id, match_method, match_confidence, verified
        ) values (r.barcode, v_id, 'legacy_isolated', 1.0, r.gs1_verified);
    end loop;
end $$;

-- Rebuilds one canonical offer set, then materializes it under every known alias barcode.
-- Therefore GET /product/{any_alias_barcode} returns prices collected under all equivalent barcodes.
create or replace function rebuild_product_snapshots()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    v_count integer;
begin
    with latest_per_store as (
        select distinct on (pa.canonical_product_id, pp.retailer_id, pp.branch_key)
            pa.canonical_product_id,
            pp.barcode as observed_barcode,
            pp.retailer_id,
            pp.price,
            pp.currency,
            pp.branch_key,
            pp.source_url,
            pp.valid_from as price_changed_at,
            pp.last_seen_at,
            r.name_ar as retailer
        from price_periods pp
        join product_aliases pa on pa.barcode = pp.barcode
        join retailers r on r.id = pp.retailer_id
        where pp.last_seen_at >= now() - interval '36 hours'
        order by pa.canonical_product_id, pp.retailer_id, pp.branch_key, pp.last_seen_at desc
    ), offers as (
        select
            canonical_product_id,
            jsonb_agg(
                jsonb_build_object(
                    'retailer', retailer,
                    'price', price,
                    'currency', currency,
                    'updated_at', price_changed_at,
                    'branch_key', branch_key,
                    'source_url', source_url,
                    'barcode', observed_barcode
                ) order by price asc
            ) as offers,
            count(*)::int as source_count
        from latest_per_store
        group by canonical_product_id
    ), latest_any as (
        select distinct on (canonical_product_id)
            canonical_product_id,
            observed_barcode,
            retailer,
            price,
            currency,
            price_changed_at,
            last_seen_at
        from latest_per_store
        order by canonical_product_id, last_seen_at desc
    ), stats as (
        select
            pa.canonical_product_id,
            min(pp.price) as min_30d,
            max(pp.price) as max_30d
        from price_periods pp
        join product_aliases pa on pa.barcode = pp.barcode
        where coalesce(pp.valid_to, pp.last_seen_at) >= now() - interval '30 days'
          and pp.valid_from <= now()
        group by pa.canonical_product_id
    ), aliases as (
        select
            canonical_product_id,
            jsonb_agg(barcode order by barcode) as matched_barcodes,
            count(*)::int as alias_count
        from product_aliases
        group by canonical_product_id
    ), built_by_identity as (
        select
            cp.id as canonical_product_id,
            coalesce(cp.canonical_name_ar, meta.name_ar) as name_ar,
            coalesce(cp.canonical_name_en, meta.name_en) as name_en,
            coalesce(cp.image_url, meta.image_url) as image_url,
            cp.product_info,
            la.price,
            coalesce(la.currency, 'SAR') as currency,
            la.retailer,
            la.price_changed_at,
            s.min_30d,
            s.max_30d,
            coalesce(o.source_count, 0) as source_count,
            coalesce(o.offers, '[]'::jsonb) as offers,
            coalesce(a.matched_barcodes, '[]'::jsonb) as matched_barcodes,
            coalesce(a.alias_count, 1) as alias_count,
            la.last_seen_at
        from canonical_products cp
        left join lateral (
            select p.name_ar, p.name_en, p.image_url
            from product_aliases pa2
            join products p on p.barcode = pa2.barcode
            where pa2.canonical_product_id = cp.id
            order by p.updated_at desc
            limit 1
        ) meta on true
        left join latest_any la on la.canonical_product_id = cp.id
        left join stats s on s.canonical_product_id = cp.id
        left join offers o on o.canonical_product_id = cp.id
        left join aliases a on a.canonical_product_id = cp.id
    ), built_per_barcode as (
        select
            pa.barcode,
            jsonb_build_object(
                'barcode', pa.barcode,
                'canonical_product_id', b.canonical_product_id,
                'matched_barcodes', b.matched_barcodes,
                'name_ar', b.name_ar,
                'name_en', b.name_en,
                'image_url', b.image_url,
                'current_price', b.price,
                'currency', b.currency,
                'retailer', b.retailer,
                'price_updated_at', b.price_changed_at,
                'min_30d', b.min_30d,
                'max_30d', b.max_30d,
                'source_count', b.source_count,
                'confidence', case
                    when b.last_seen_at >= now() - interval '14 hours' then 1.0
                    when b.last_seen_at >= now() - interval '26 hours' then 0.9
                    when b.last_seen_at is not null then 0.7
                    else 0.5
                end,
                'offers', b.offers,
                'product_info', b.product_info
            ) as payload
        from product_aliases pa
        join built_by_identity b on b.canonical_product_id = pa.canonical_product_id
    )
    insert into product_snapshots (barcode, payload, payload_hash, updated_at)
    select barcode, payload, md5(payload::text), now()
    from built_per_barcode
    on conflict (barcode) do update
    set payload = excluded.payload,
        payload_hash = excluded.payload_hash,
        updated_at = excluded.updated_at
    where product_snapshots.payload_hash is distinct from excluded.payload_hash;

    get diagnostics v_count = row_count;

    insert into system_state (key, value, updated_at)
    values (
        'last_price_refresh',
        jsonb_build_object('completed_at', now(), 'changed_snapshots', v_count),
        now()
    )
    on conflict (key) do update
    set value = excluded.value,
        updated_at = excluded.updated_at;

    delete from price_periods
    where valid_to is not null
      and valid_to < now() - interval '35 days';

    return v_count;
end;
$$;

-- Expand the existing read model with canonical identity fields and product information.
create or replace view product_price_snapshot as
select
    barcode,
    nullif(payload ->> 'canonical_product_id', '')::bigint as canonical_product_id,
    coalesce(payload -> 'matched_barcodes', '[]'::jsonb) as matched_barcodes,
    payload ->> 'name_ar' as name_ar,
    payload ->> 'name_en' as name_en,
    payload ->> 'image_url' as image_url,
    nullif(payload ->> 'current_price', '')::double precision as current_price,
    coalesce(payload ->> 'currency', 'SAR') as currency,
    payload ->> 'retailer' as retailer,
    payload ->> 'price_updated_at' as price_updated_at,
    nullif(payload ->> 'min_30d', '')::double precision as min_30d,
    nullif(payload ->> 'max_30d', '')::double precision as max_30d,
    coalesce((payload ->> 'source_count')::int, 0) as source_count,
    nullif(payload ->> 'confidence', '')::double precision as confidence,
    coalesce(payload -> 'offers', '[]'::jsonb) as offers,
    payload -> 'product_info' as product_info
from product_snapshots;

alter table canonical_products enable row level security;
alter table product_aliases enable row level security;
revoke all on canonical_products from anon, authenticated;
revoke all on product_aliases from anon, authenticated;
