create table if not exists retailers (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    name_ar text not null,
    name_en text not null,
    base_url text,
    active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists products (
    barcode text primary key,
    name_ar text,
    name_en text,
    brand text,
    image_url text,
    gs1_verified boolean not null default false,
    updated_at timestamptz not null default now(),
    constraint products_barcode_digits check (barcode ~ '^[0-9]{8,14}$')
);

-- Exact retailer page mapped to an exact verified GTIN/barcode.
-- The 12-hour job refreshes these URLs instead of rediscovering the whole web.
create table if not exists retailer_product_sources (
    id bigint generated by default as identity primary key,
    barcode text not null references products(barcode) on delete cascade,
    retailer_id bigint not null references retailers(id) on delete cascade,
    source_url text not null,
    branch_key text not null default 'online',
    active boolean not null default true,
    last_checked_at timestamptz,
    last_error text,
    created_at timestamptz not null default now(),
    unique (retailer_id, source_url)
);

create index if not exists retailer_product_sources_active_idx
    on retailer_product_sources (active, retailer_id, last_checked_at);

-- Compact history: one row represents a continuous period at the same price.
-- Every 12-hour check updates last_seen_at. A new row is created only if the price changes.
create table if not exists price_periods (
    id bigint generated by default as identity primary key,
    barcode text not null references products(barcode) on delete cascade,
    retailer_id bigint not null references retailers(id) on delete cascade,
    branch_key text not null default 'online',
    price numeric(12,2) not null check (price >= 0),
    currency text not null default 'SAR',
    source_url text,
    valid_from timestamptz not null,
    valid_to timestamptz,
    last_seen_at timestamptz not null,
    created_at timestamptz not null default now()
);

create index if not exists price_periods_barcode_time_idx
    on price_periods (barcode, last_seen_at desc);

create index if not exists price_periods_retailer_time_idx
    on price_periods (retailer_id, last_seen_at desc);

create unique index if not exists price_periods_one_open_idx
    on price_periods (barcode, retailer_id, branch_key)
    where valid_to is null;

-- Hot read model used by the app and replicated to D1/Firebase.
-- updated_at changes only when the JSON payload actually changes.
create table if not exists product_snapshots (
    barcode text primary key references products(barcode) on delete cascade,
    payload jsonb not null,
    payload_hash text not null,
    updated_at timestamptz not null default now()
);

create table if not exists system_state (
    key text primary key,
    value jsonb not null,
    updated_at timestamptz not null default now()
);

create or replace function record_retailer_price(
    p_barcode text,
    p_retailer_slug text,
    p_branch_key text,
    p_price numeric,
    p_currency text default 'SAR',
    p_source_url text default null,
    p_observed_at timestamptz default now()
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_retailer_id bigint;
    v_current price_periods%rowtype;
begin
    select id into v_retailer_id
    from retailers
    where slug = p_retailer_slug and active = true;

    if v_retailer_id is null then
        raise exception 'Unknown or inactive retailer: %', p_retailer_slug;
    end if;

    select * into v_current
    from price_periods
    where barcode = p_barcode
      and retailer_id = v_retailer_id
      and branch_key = coalesce(nullif(p_branch_key, ''), 'online')
      and valid_to is null
    for update;

    if found and v_current.price = p_price and v_current.currency = coalesce(nullif(p_currency, ''), 'SAR') then
        update price_periods
        set last_seen_at = p_observed_at,
            source_url = coalesce(p_source_url, source_url)
        where id = v_current.id;
        return;
    end if;

    if found then
        update price_periods
        set valid_to = p_observed_at,
            last_seen_at = greatest(last_seen_at, p_observed_at)
        where id = v_current.id;
    end if;

    insert into price_periods (
        barcode, retailer_id, branch_key, price, currency, source_url,
        valid_from, valid_to, last_seen_at
    ) values (
        p_barcode,
        v_retailer_id,
        coalesce(nullif(p_branch_key, ''), 'online'),
        p_price,
        coalesce(nullif(p_currency, ''), 'SAR'),
        p_source_url,
        p_observed_at,
        null,
        p_observed_at
    );
end;
$$;

create or replace function rebuild_product_snapshots()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    v_count integer;
begin
    with latest_per_store as (
        select distinct on (pp.barcode, pp.retailer_id)
            pp.barcode,
            pp.retailer_id,
            pp.price,
            pp.currency,
            pp.branch_key,
            pp.source_url,
            pp.valid_from as price_changed_at,
            pp.last_seen_at,
            r.name_ar as retailer
        from price_periods pp
        join retailers r on r.id = pp.retailer_id
        where pp.last_seen_at >= now() - interval '36 hours'
        order by pp.barcode, pp.retailer_id, pp.last_seen_at desc
    ), offers as (
        select
            barcode,
            jsonb_agg(
                jsonb_build_object(
                    'retailer', retailer,
                    'price', price,
                    'currency', currency,
                    'updated_at', price_changed_at,
                    'branch_key', branch_key,
                    'source_url', source_url
                ) order by price asc
            ) as offers,
            count(*)::int as source_count
        from latest_per_store
        group by barcode
    ), latest_any as (
        select distinct on (barcode)
            barcode,
            retailer,
            price,
            currency,
            price_changed_at,
            last_seen_at
        from latest_per_store
        order by barcode, last_seen_at desc
    ), stats as (
        select
            barcode,
            min(price) as min_30d,
            max(price) as max_30d
        from price_periods
        where coalesce(valid_to, last_seen_at) >= now() - interval '30 days'
          and valid_from <= now()
        group by barcode
    ), built as (
        select
            p.barcode,
            jsonb_build_object(
                'barcode', p.barcode,
                'name_ar', p.name_ar,
                'name_en', p.name_en,
                'image_url', p.image_url,
                'current_price', la.price,
                'currency', coalesce(la.currency, 'SAR'),
                'retailer', la.retailer,
                'price_updated_at', la.price_changed_at,
                'min_30d', s.min_30d,
                'max_30d', s.max_30d,
                'source_count', coalesce(o.source_count, 0),
                'confidence', case
                    when la.last_seen_at >= now() - interval '14 hours' then 1.0
                    when la.last_seen_at >= now() - interval '26 hours' then 0.9
                    when la.last_seen_at is not null then 0.7
                    else 0.5
                end,
                'offers', coalesce(o.offers, '[]'::jsonb)
            ) as payload
        from products p
        left join latest_any la on la.barcode = p.barcode
        left join stats s on s.barcode = p.barcode
        left join offers o on o.barcode = p.barcode
    )
    insert into product_snapshots (barcode, payload, payload_hash, updated_at)
    select barcode, payload, md5(payload::text), now()
    from built
    on conflict (barcode) do update
    set payload = excluded.payload,
        payload_hash = excluded.payload_hash,
        updated_at = excluded.updated_at
    where product_snapshots.payload_hash is distinct from excluded.payload_hash;

    get diagnostics v_count = row_count;

    insert into system_state (key, value, updated_at)
    values (
        'last_price_refresh',
        jsonb_build_object('completed_at', now(), 'changed_snapshots', v_count),
        now()
    )
    on conflict (key) do update
    set value = excluded.value,
        updated_at = excluded.updated_at;

    -- Only 30-day history is exposed; older closed periods cannot affect the UI.
    delete from price_periods
    where valid_to is not null
      and valid_to < now() - interval '35 days';

    return v_count;
end;
$$;

-- Read-only view shaped exactly like the Android ProductSnapshot DTO.
create or replace view product_price_snapshot as
select
    barcode,
    payload ->> 'name_ar' as name_ar,
    payload ->> 'name_en' as name_en,
    payload ->> 'image_url' as image_url,
    nullif(payload ->> 'current_price', '')::double precision as current_price,
    coalesce(payload ->> 'currency', 'SAR') as currency,
    payload ->> 'retailer' as retailer,
    payload ->> 'price_updated_at' as price_updated_at,
    nullif(payload ->> 'min_30d', '')::double precision as min_30d,
    nullif(payload ->> 'max_30d', '')::double precision as max_30d,
    coalesce((payload ->> 'source_count')::int, 0) as source_count,
    nullif(payload ->> 'confidence', '')::double precision as confidence,
    coalesce(payload -> 'offers', '[]'::jsonb) as offers
from product_snapshots;

alter table retailers enable row level security;
alter table products enable row level security;
alter table retailer_product_sources enable row level security;
alter table price_periods enable row level security;
alter table product_snapshots enable row level security;
alter table system_state enable row level security;

drop policy if exists "public read retailers" on retailers;
create policy "public read retailers" on retailers for select using (true);

drop policy if exists "public read products" on products;
create policy "public read products" on products for select using (true);

drop policy if exists "public read snapshots" on product_snapshots;
create policy "public read snapshots" on product_snapshots for select using (true);

drop policy if exists "public read system state" on system_state;
create policy "public read system state" on system_state for select using (true);

grant select on product_price_snapshot to anon, authenticated;
revoke all on retailer_product_sources from anon, authenticated;
revoke all on price_periods from anon, authenticated;
revoke all on product_snapshots from anon, authenticated;
grant select on product_snapshots to anon, authenticated;
grant select on system_state to anon, authenticated;
