create table if not exists retailers (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    name_ar text not null,
    name_en text not null,
    base_url text,
    active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists products (
    barcode text primary key,
    name_ar text,
    name_en text,
    brand text,
    image_url text,
    gs1_verified boolean not null default false,
    updated_at timestamptz not null default now(),
    constraint products_barcode_digits check (barcode ~ '^[0-9]{8,14}$')
);

create table if not exists price_observations (
    id bigint generated by default as identity primary key,
    barcode text not null references products(barcode) on delete cascade,
    retailer_id bigint not null references retailers(id) on delete cascade,
    branch_key text not null default 'online',
    price numeric(12,2) not null check (price >= 0),
    currency text not null default 'SAR',
    source_url text,
    observed_at timestamptz not null default now(),
    source_hash text,
    created_at timestamptz not null default now()
);

create index if not exists price_observations_barcode_time_idx
    on price_observations (barcode, observed_at desc);

create index if not exists price_observations_retailer_time_idx
    on price_observations (retailer_id, observed_at desc);

create unique index if not exists price_observations_dedupe_idx
    on price_observations (barcode, retailer_id, branch_key, observed_at, coalesce(source_hash, ''));

create or replace view product_price_snapshot as
with latest as (
    select distinct on (po.barcode)
        po.barcode,
        po.price as current_price,
        po.currency,
        po.observed_at as price_updated_at,
        r.name_ar as retailer
    from price_observations po
    join retailers r on r.id = po.retailer_id
    order by po.barcode, po.observed_at desc
), stats as (
    select
        po.barcode,
        min(po.price) filter (where po.observed_at >= now() - interval '30 days') as min_30d,
        max(po.price) filter (where po.observed_at >= now() - interval '30 days') as max_30d,
        count(distinct po.retailer_id) filter (where po.observed_at >= now() - interval '30 days')::int as source_count
    from price_observations po
    group by po.barcode
)
select
    p.barcode,
    p.name_ar,
    p.name_en,
    p.image_url,
    l.current_price,
    coalesce(l.currency, 'SAR') as currency,
    l.retailer,
    l.price_updated_at,
    s.min_30d,
    s.max_30d,
    coalesce(s.source_count, 0) as source_count,
    case
        when l.price_updated_at >= now() - interval '6 hours' then 1.0
        when l.price_updated_at >= now() - interval '24 hours' then 0.9
        when l.price_updated_at >= now() - interval '72 hours' then 0.75
        else 0.5
    end::double precision as confidence
from products p
left join latest l on l.barcode = p.barcode
left join stats s on s.barcode = p.barcode;

alter table retailers enable row level security;
alter table products enable row level security;
alter table price_observations enable row level security;

drop policy if exists "public read retailers" on retailers;
create policy "public read retailers" on retailers for select using (true);

drop policy if exists "public read products" on products;
create policy "public read products" on products for select using (true);

grant select on product_price_snapshot to anon, authenticated;
