import { createClient } from "npm:@supabase/supabase-js@2";

const UA = "SaudiSupermarketIdentityBot/2.1 (+public product identity price refresh)";
const enc = new TextEncoder();

type Cfg = { slug:string; base:string; sitemaps:string[]; seeds:string[]; product:RegExp; delay:number };
type Identity = { key:string; variant:string|null; sizeValue:number; sizeUnit:string; packCount:number };
type Parsed = Identity & { nameAr:string|null; nameEn:string|null; brand:string; image:string|null; price:number; currency:string; url:string; parser:string };

const C:Record<string,Cfg> = {
  carrefour:{slug:"carrefour",base:"https://www.carrefourksa.com/",sitemaps:["https://www.carrefourksa.com/sitemap.xml"],seeds:["https://www.carrefourksa.com/mafsau/en/"],product:/\/p\/[0-9]+/i,delay:1000},
  lulu:{slug:"lulu",base:"https://gcc.luluhypermarket.com/en-sa/",sitemaps:["https://gcc.luluhypermarket.com/en-sa/sitemap.xml"],seeds:["https://gcc.luluhypermarket.com/en-sa/list/","https://gcc.luluhypermarket.com/en-sa/grocery-food-cupboard","https://gcc.luluhypermarket.com/en-sa/"],product:/\/en-sa\/.+\/p\//i,delay:1000},
  danube:{slug:"danube",base:"https://danube.sa/",sitemaps:[],seeds:["https://danube.sa/en/departments","https://danube.sa/en/"],product:/\/products\//i,delay:1000},
  bindawood:{slug:"bindawood",base:"https://www.bindawood.sa/",sitemaps:[],seeds:["https://www.bindawood.sa/"],product:/\/(products|product)\//i,delay:1000},
  tamimi:{slug:"tamimi",base:"https://shop.tamimimarkets.com/en/",sitemaps:[],seeds:["https://shop.tamimimarkets.com/en/"],product:/\/en\/product\//i,delay:1000},
  panda:{slug:"panda",base:"https://plus.panda.sa/",sitemaps:[],seeds:["https://plus.panda.sa/"],product:/\/(product|products)\//i,delay:1000},
  othaim:{slug:"othaim",base:"https://www.othaimmarkets.com/",sitemaps:[],seeds:["https://www.othaimmarkets.com/"],product:/\/(product|products)\//i,delay:1000},
  farm:{slug:"farm",base:"https://www.farm.com.sa/",sitemaps:[],seeds:["https://www.farm.com.sa/"],product:/\/(product|products)\//i,delay:1000},
  spinneys:{slug:"spinneys",base:"https://www.spinneys.com/en-sa/",sitemaps:[],seeds:["https://www.spinneys.com/en-sa/"],product:/\/en-sa\/catalogue\/[^/]+_[0-9]+\//i,delay:1000},
  alraya:{slug:"alraya",base:"https://www.alraya.com.sa/",sitemaps:[],seeds:["https://www.alraya.com.sa/"],product:/\/(product|products)\//i,delay:1000}
};

const STOP = new Set(["can","cans","bottle","bottles","pet","pack","packs","piece","pieces","pc","pcs","ml","ltr","liter","litre","g","gm","gram","kg","علبة","علب","عبوة","عبوات","زجاجة","زجاجات","حبة","حبات","مل","لتر","جرام","غرام","كيلو","كجم"]);
const VAR:Record<string,string[]> = {zero:["zero","زيرو","صفر"],diet:["diet","دايت","حمية"],light:["light","لايت","خفيف"],original:["original","regular","classic","اصلي","أصلي","عادي","كلاسيك"],cherry:["cherry","كرز"],vanilla:["vanilla","فانيلا"],lemon:["lemon","ليمون"],lime:["lime","لايم"]};
const SIZES:Array<[RegExp,string,number]> = [[/\b(\d+(?:[.,]\d+)?)\s*(?:ml|مل|مليلتر|millilit(?:er|re)s?)\b/i,"ml",1],[/\b(\d+(?:[.,]\d+)?)\s*(?:l|ltr|liter|litre|لتر)\b/i,"ml",1000],[/\b(\d+(?:[.,]\d+)?)\s*(?:g|gm|gram|جرام|غرام)\b/i,"g",1],[/\b(\d+(?:[.,]\d+)?)\s*(?:kg|kilogram|كيلو|كجم)\b/i,"g",1000]];
const PACKS = [/(?:^|\D)(\d{1,3})\s*[x×]\s*/i,/(?:pack|pk|عبوة|عبوات|حبة|حبات)\s*(?:of\s*)?(\d{1,3})(?!\d)/i,/(?:^|\D)(\d{1,3})\s*(?:pack|pk|pcs|pieces|حبة|حبات|عبوة|عبوات)(?!\w)/i];

function secretKey(){const modern=Deno.env.get("SUPABASE_SECRET_KEYS");if(modern){try{const parsed=JSON.parse(modern);if(parsed?.default)return String(parsed.default)}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??""}
async function hex(v:string){const h=await crypto.subtle.digest("SHA-256",enc.encode(v));return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function host(v:string){try{return new URL(v).hostname.toLowerCase().replace(/^www\./,"")}catch{return""}}
async function get(url:string,accept="text/html,application/xhtml+xml,*/*;q=0.8"){try{const r=await fetch(url,{headers:{"User-Agent":UA,Accept:accept,"Accept-Language":"ar-SA,ar;q=0.9,en;q=0.8"},redirect:"follow",signal:AbortSignal.timeout(12000)});return r.ok?await r.text():null}catch{return null}}

function rules(txt:string){const allow:string[]=[],deny:string[]=[],maps:string[]=[];let active=false;for(const raw of txt.split(/\r?\n/)){const line=raw.split("#",1)[0].trim();if(!line)continue;const i=line.indexOf(":");if(i<0)continue;const k=line.slice(0,i).trim().toLowerCase(),v=line.slice(i+1).trim();if(k==="sitemap"&&v){maps.push(v);continue}if(k==="user-agent"){const a=v.toLowerCase();active=a==="*"||UA.toLowerCase().startsWith(a);continue}if(!active)continue;if(k==="allow"&&v)allow.push(v);if(k==="disallow"&&v)deny.push(v)}return{allow,deny,maps}}
function allowed(url:string,r:{allow:string[];deny:string[]}){let p="/";try{const u=new URL(url);p=u.pathname+u.search}catch{return false}const matches=(q:string)=>{if(!q)return false;const e="^"+q.replace(/[.+?^${}()|[\]\\]/g,"\\$&").replace(/\*/g,".*").replace(/\$$/,"$");try{return new RegExp(e).test(p)}catch{return p.startsWith(q)}};const a=r.allow.filter(matches).sort((x,y)=>y.length-x.length)[0]??"",d=r.deny.filter(matches).sort((x,y)=>y.length-x.length)[0]??"";return !d||a.length>=d.length}
function normal(raw:string,base:string,cfg:Cfg,prod:boolean){const v=raw.trim().replace(/\\\//g,"/").replace(/&amp;/g,"&");if(!v||/^(javascript:|mailto:|tel:)/i.test(v))return null;try{const u=new URL(v,base);u.hash="";if(!["http:","https:"].includes(u.protocol)||host(u.toString())!==host(cfg.base))return null;if(prod&&!cfg.product.test(u.pathname))return null;return u.toString()}catch{return null}}
function htmlUrls(txt:string,base:string,cfg:Cfg,prod:boolean){const n=txt.replace(/\\\//g,"/"),out:string[]=[];const raws=[...[...n.matchAll(/href\s*=\s*["']([^"']+)["']/gi)].map(x=>x[1]),...[...n.matchAll(/(?:(?:https?:)?\/\/[^"'<>\\\s]+|\/[A-Za-z0-9_%?=&+.,:@~!$'()*;\-/]+)/gi)].map(x=>x[0])];for(const raw of raws){const u=normal(raw,base,cfg,prod);if(u&&!out.includes(u))out.push(u)}return out}
function locs(x:string){return [...x.matchAll(/<loc>([\s\S]*?)<\/loc>/gi)].map(m=>m[1].replace(/&amp;/g,"&").trim()).filter(Boolean)}
function score(u:string){return /product|catalog|sku/i.test(u)?100:/sitemap/i.test(u)?5:0}
async function discover(cfg:Cfg,robot:string,max:number){const rr=rules(robot),root=new URL(cfg.base).origin,q=[...new Set([...cfg.sitemaps,...rr.maps.filter(x=>host(x)===host(cfg.base)),`${root}/sitemap.xml`,`${root}/sitemap_index.xml`,`${root}/sitemap-index.xml`])],seen=new Set<string>(),products:string[]=[],browse:string[]=[];let docs=0;while(q.length&&docs<12&&products.length<max*5){q.sort((a,b)=>score(b)-score(a));const s=q.shift()!;if(seen.has(s)||host(s)!==host(cfg.base))continue;seen.add(s);const x=await get(s,"application/xml,text/xml,*/*;q=0.8");if(!x||(!/<urlset/i.test(x)&&!/<sitemapindex/i.test(x)))continue;docs++;const ls=locs(x);if(/<sitemapindex/i.test(x))q.push(...ls.filter(z=>host(z)===host(cfg.base)&&!seen.has(z)));else for(const z of ls){const u=normal(z,cfg.base,cfg,true);if(u&&!products.includes(u))products.push(u)}}for(const seed of cfg.seeds){if(!allowed(seed,rr))continue;const x=await get(seed);if(!x)continue;for(const u of htmlUrls(x,seed,cfg,true))if(!products.includes(u))products.push(u);for(const u of htmlUrls(x,seed,cfg,false)){let p="";try{p=new URL(u).pathname.toLowerCase()}catch{continue}if(cfg.product.test(p)||/login|account|cart|checkout|wishlist|compare|search|api\//.test(p))continue;if(allowed(u,rr)&&!browse.includes(u))browse.push(u);if(browse.length>=12)break}}for(const page of browse.slice(0,8)){if(products.length>=max*5)break;const x=await get(page);if(!x)continue;for(const u of htmlUrls(x,page,cfg,true)){if(!products.includes(u))products.push(u);if(products.length>=max*5)break}}return{products,diag:{sitemap_docs:docs,browse_pages:browse.length,product_candidates:products.length}}}

function decodeEntities(s:string){return s.replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16)))}
function text(s:string){return decodeEntities(s.replace(/<script\b[\s\S]*?<\/script>/gi," ").replace(/<style\b[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ")).replace(/\s+/g," ").trim()}
function clean(v:unknown){const s=v==null?"":String(v).replace(/\s+/g," ").trim();return s||null}
function meta(h:string,key:string){const e=key.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");for(const re of [new RegExp(`<meta\\b[^>]*(?:property|name|itemprop>=["']${e}["'][^>]*content=["']([^"']+)["'][^>]*>`,`i`),new RegExp(`<meta\\b[^>]*content=["']([^"']+)["'][^>]*(?:property|name|itemprop)=["']${e}["'][^>]*>`,`i`)]){const m=h.match(re);if(m)return decodeEntities(m[1].trim())}return null}
function productLD(h:string){const out:Record<string,unknown>[]=[];for(const m of h.matchAll(/<script\b[^>]*type=["'][^"']*ld\+json[^"']*["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const stack:unknown[]=[JSON.parse(m[1].trim())];while(stack.length){const v=stack.pop();if(Array.isArray(v)){stack.push(...v);continue}if(!v||typeof v!=="object")continue;const o=v as Record<string,unknown>;if(Array.isArray(o["@graph"]))stack.push(...o["@graph"] as unknown[]);const t=o["@type"],ts=Array.isArray(t)?t.map(x=>String(x).toLowerCase()):[String(t??"").toLowerCase()];if(ts.includes("product"))out.push(o)}}catch{}}return out}
function brand(p:Record<string,unknown>){const b=p.brand;if(typeof b==="string")return clean(b);if(b&&typeof b==="object"&&!Array.isArray(b))return clean((b as Record<string,unknown>).name);if(Array.isArray(b))for(const x of b){if(typeof x==="string")return clean(x);if(x&&typeof x==="object"){const n=clean((x as Record<string,unknown>).name);if(n)return n}}return null}
function image(p:Record<string,unknown>,u:string){let i:unknown=p.image;if(Array.isArray(i))i=i.find(x=>typeof x==="string");if(i&&typeof i==="object")i=(i as Record<string,unknown>).url??(i as Record<string,unknown>).contentUrl;if(typeof i!=="string"||!i.trim())return null;try{return new URL(i.trim(),u).toString()}catch{return null}}
function price(v:unknown){if(v==null)return null;const m=String(v).trim().replace(/٬/g,"").replace(/,/g,"").replace(/٫/g,".").match(/(?:^|\D)(\d{1,7}(?:\.\d{1,2})?)(?:\D|$)/);if(!m)return null;const n=Number(m[1]);return Number.isFinite(n)&&n>0&&n<=100000?Math.round(n*100)/100:null}
function offer(p:Record<string,unknown>){const o=p.offers,x=Array.isArray(o)?o:o&&typeof o==="object"?[o]:[];for(const i of x){if(!i||typeof i!=="object")continue;const z=i as Record<string,unknown>,n=price(z.price??z.lowPrice);if(n!==null)return{n,c:String(z.priceCurrency??"SAR").toUpperCase()}}return{n:null,c:"SAR"}}
function norm(s:string|null){return(s??"").normalize("NFKC").toLowerCase().trim().replace(/[أإآ]/g,"ا").replace(/ة/g,"ه").replace(/ى/g,"ي").replace(/[^0-9a-z\u0600-\u06ff]+/gi," ").replace(/\s+/g," ").trim()}
async function identity(name:string|null,b:string|null):Promise<Identity|null>{const source=[name,b].filter(Boolean).join(" "),nb=norm(b);let sv:number|null=null,su:string|null=null;for(const[p,u,m]of SIZES){const x=source.match(p);if(x){const n=Number(x[1].replace(",","."))*m;if(n>0&&n<=100000){sv=Math.round(n*1000)/1000;su=u;break}}}let pc=1;for(const p of PACKS){const x=source.match(p);if(x){const n=Number(x[1]);if(n>=1&&n<=100){pc=n;break}}}const toks=new Set(norm(source).split(" ").filter(Boolean)),vs:string[]=[];for(const[k,w]of Object.entries(VAR))if(w.some(q=>toks.has(norm(q))))vs.push(k);const v=vs.length?[...new Set(vs)].sort().join("+"):null;if(!nb||sv===null||!su)return null;let stripped=name??"";for(const[p]of SIZES)stripped=stripped.replace(p," ");for(const p of PACKS)stripped=stripped.replace(p," ");const bt=new Set(nb.split(" ")),vt=new Set(Object.values(VAR).flat().map(norm)),fam=[...new Set(norm(stripped).split(" ").filter(t=>t.length>1&&!/^\d+$/.test(t)&&!STOP.has(t)&&!bt.has(t)&&!vt.has(t)))].sort().slice(0,6);if(!fam.length&&!v)return null;const raw=[nb,v??"standard",`${String(sv)}:${su}`,String(pc),fam.join(",")].join("|"),d=(await hex(raw)).slice(0,32);return{key:`v2:${d}`,variant:v,sizeValue:sv,sizeUnit:su,packCount:pc}}

async function jsonLdExtract(h:string,u:string):Promise<Parsed|null>{const ps=productLD(h);if(ps.length!==1)return null;const p=ps[0],name=clean(p.name),b=brand(p),of=offer(p);if(!name||!b||of.n===null)return null;const id=await identity(name,b);if(!id)return null;return{nameAr:/[\u0600-\u06ff]/.test(name)?name:null,nameEn:/[\u0600-\u06ff]/.test(name)?null:name,brand:b,image:image(p,u),price:of.n,currency:of.c,url:u,parser:"jsonld",...id}}
async function luluExtract(h:string,u:string):Promise<Parsed|null>{const hm=h.match(/<h1\b[^>]*>([\s\S]{1,1200}?)<\/h1>/i);if(!hm||hm.index==null)return null;const name=text(hm[1]);if(!name||name.length>240)return null;const before=h.slice(Math.max(0,hm.index-5000),hm.index);let b:string|null=null;const bm=before.match(/View\s*all\s*products\s*from[\s\S]{0,1200}?<a\b[^>]*>([\s\S]{1,300}?)<\/a>/i);if(bm)b=text(bm[1]);if(!b){const p=text(before).match(/View\s*all\s*products\s*from\s+([A-Za-z0-9&'’._\- ]{2,80})\s*$/i);if(p)b=p[1].trim()}if(!b)return null;let amount=price(meta(h,"product:price:amount")??meta(h,"price")??meta(h,"og:price:amount"));if(amount===null){const endTag=hm.index+hm[0].length;let after=h.slice(endTag,endTag+6000);const marker=after.search(/Selected\s*Pack\s*Quantity|Product\s*Summary|Product\s*Information/i);if(marker>=0)after=after.slice(0,marker);const p=text(after).match(/(?:^|\s)(\d{1,5}(?:[.,]\d{1,2})?)(?=\s|$)/);if(p)amount=price(p[1])}if(amount===null)return null;const id=await identity(name,b);if(!id)return null;const og=meta(h,"og:image");let img:string|null=null;if(og){try{img=new URL(og,u).toString()}catch{}}return{nameAr:/[\u0600-\u06ff]/.test(name)?name:null,nameEn:/[\u0600-\u06ff]/.test(name)?null:name,brand:b,image:img,price:amount,currency:(meta(h,"product:price:currency")??"SAR").toUpperCase(),url:u,parser:"lulu_h1_brand_price",...id}}
async function extract(h:string,u:string,slug:string){const structured=await jsonLdExtract(h,u);if(structured)return structured;if(slug==="lulu")return await luluExtract(h,u);return null}
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));

Deno.serve(async(req:Request)=>{const start=Date.now(),projectUrl=Deno.env.get("SUPABASE_URL")??"",key=secretKey();if(!projectUrl||!key)return Response.json({error:"server_config_missing"},{status:503});const db=createClient(projectUrl,key,{auth:{persistSession:false,autoRefreshToken:false}}),token=req.headers.get("x-ingest-token")??"",{data:ctl}=await db.from("ingest_control").select("value").eq("key","cron_token_sha256").maybeSingle();if(!ctl?.value||(await hex(token))!==ctl.value)return Response.json({error:"unauthorized"},{status:401});let body:any={};try{body=await req.json()}catch{}const cfg=C[String(body.retailer??"")];if(!cfg)return Response.json({error:"unknown_retailer"},{status:400});const max=Math.max(1,Math.min(Number(body.max_pages??12)||12,20)),robot=await get(new URL("/robots.txt",cfg.base).toString(),"text/plain,*/*;q=0.8");if(!robot)return Response.json({retailer:cfg.slug,status:"robots_unavailable",recorded:0});const rr=rules(robot),{data:r}=await db.from("retailers").select("id").eq("slug",cfg.slug).eq("active",true).maybeSingle();if(!r)return Response.json({error:"retailer_not_seeded"},{status:409});const direct=(Array.isArray(body.urls)?body.urls:[]).map((x:unknown)=>normal(String(x),cfg.base,cfg,true)).filter((x:string|null):x is string=>!!x).filter((x:string,i:number,a:string[])=>a.indexOf(x)===i).slice(0,max);const {data:knownRows}=await db.from("retailer_identity_sources").select("id,identity_key,source_url,branch_key,last_checked_at").eq("retailer_id",r.id).eq("active",true).order("last_checked_at",{ascending:true,nullsFirst:true}).limit(Math.ceil(max/2));const known=new Set((knownRows??[]).map((x:any)=>String(x.source_url))),disc=direct.length?{products:direct,diag:{sitemap_docs:0,browse_pages:0,product_candidates:direct.length,direct_test:true}}:await discover(cfg,robot,max),fresh=disc.products.filter(x=>direct.length||!known.has(x)).slice(0,direct.length?max:Math.ceil(max/2));let recorded=0,refreshed=0,rejected=0,failed=0;const accepted:Array<{url:string;name:string|null;brand:string;price:number;identity:string;parser:string}>=[];
async function write(u:string,expectedIdentity:string|null,sourceId:number|null,branch="online"){if(!allowed(u,rr)){rejected++;return}const h=await get(u);if(!h){failed++;return}const p=await extract(h,u,cfg.slug);if(!p||(expectedIdentity&&p.key!==expectedIdentity)){rejected++;if(sourceId)await db.from("retailer_identity_sources").update({last_checked_at:new Date().toISOString(),last_error:"identity_not_verified_on_page"}).eq("id",sourceId);return}const{error}=await db.rpc("record_identity_price",{p_identity_key:p.key,p_name_ar:p.nameAr,p_name_en:p.nameEn,p_brand:p.brand,p_variant:p.variant,p_net_content_value:p.sizeValue,p_net_content_unit:p.sizeUnit,p_pack_count:p.packCount,p_image_url:p.image,p_retailer_slug:cfg.slug,p_branch_key:branch,p_price:p.price,p_currency:p.currency,p_source_url:u});if(error){failed++;return}accepted.push({url:u,name:p.nameAr??p.nameEn,brand:p.brand,price:p.price,identity:p.key,parser:p.parser});if(sourceId){await db.from("retailer_identity_sources").update({last_checked_at:new Date().toISOString(),last_error:null}).eq("id",sourceId);refreshed++}else recorded++}
if(!direct.length)for(const s of knownRows??[]){if(Date.now()-start>115000)break;await write(String(s.source_url),String(s.identity_key),Number(s.id),String(s.branch_key??"online"));await sleep(cfg.delay)}for(const u of fresh){if(Date.now()-start>115000)break;await write(u,null,null);await sleep(cfg.delay)}const{data:changed,error:re}=await db.rpc("rebuild_product_snapshots");return Response.json({retailer:cfg.slug,recorded,refreshed,rejected,failed,changed_snapshots:re?null:changed,accepted:accepted.slice(0,5),diagnostics:disc.diag,elapsed_ms:Date.now()-start})});
