import { createClient } from "npm:@supabase/supabase-js@2";

const USER_AGENT = "MoqarinAlasaar/2.5 (Saudi barcode identity resolver; Malik05255/super_-market)";
const SFDA_BASE = "https://www.sfda.gov.sa";
const MASTER_RELEASE_BASE = "https://github.com/Malik05255/super_-market/releases/download/saudi-master-latest";
const MAX_EXTERNAL_PER_MINUTE = 30;
const RESOLVED_COOLDOWN_MS = 12 * 60 * 60 * 1000;
const MISS_COOLDOWN_MS = 5 * 60 * 1000;
const enc = new TextEncoder();

const FACTS_SOURCES = [
  { id: "open_food_facts", label: "Open Food Facts", base: "https://world.openfoodfacts.org/api/v3/product/" },
  { id: "open_products_facts", label: "Open Products Facts", base: "https://world.openproductsfacts.org/api/v3/product/" },
  { id: "open_beauty_facts", label: "Open Beauty Facts", base: "https://world.openbeautyfacts.org/api/v3/product/" },
  { id: "open_pet_food_facts", label: "Open Pet Food Facts", base: "https://world.openpetfoodfacts.org/api/v3/product/" },
] as const;

type GenericProduct = {
  barcode: string; nameAr: string | null; nameEn: string | null; brand: string | null;
  quantity: string | null; image: string | null; source: string; sourceRecordId?: string | null;
  sourceUrl?: string | null; category?: string | null; manufacturingCountry?: string | null;
  manufacturingPlaces?: string | null; ingredients?: string | null; allergens?: string[];
  nutritionGrade?: string | null; novaGroup?: number | null; positiveNotes?: string[];
  cautionNotes?: string[]; updatedAt?: string | null;
};
type MasterHit = {product: GenericProduct; evidenceSource: string; saudiSignal: string; confidence: number};

function secretKey(){const modern=Deno.env.get("SUPABASE_SECRET_KEYS");if(modern){try{const parsed=JSON.parse(modern);if(parsed?.default)return String(parsed.default)}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??""}
async function sha(value:string){const h=await crypto.subtle.digest("SHA-256",enc.encode(value));return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function validGtin(value:unknown):string|null{if(value==null)return null;const ar="٠١٢٣٤٥٦٧٨٩",fa="۰۱۲۳۴۵۶۷۸۹";const d=String(value).replace(/[٠-٩]/g,c=>String(ar.indexOf(c))).replace(/[۰-۹]/g,c=>String(fa.indexOf(c))).replace(/\D+/g,"");if(![8,12,13,14].includes(d.length))return null;let total=0;[...d.slice(0,-1)].reverse().forEach((x,i)=>total+=Number(x)*(i%2===0?3:1));return Number(d.at(-1))===(10-total%10)%10?d:null}
function restrictedCirculation(barcode:string){return(barcode.length===12&&barcode.startsWith("2"))||(barcode.length===13&&Number(barcode.slice(0,2))>=20&&Number(barcode.slice(0,2))<=29)}
function firstText(...values:unknown[]){for(const value of values){if(typeof value==="string"&&value.trim())return value.trim();if(typeof value==="number"&&Number.isFinite(value))return String(value)}return null}
function firstBrand(value:unknown){if(typeof value!=="string")return null;return value.split(",").map(x=>x.trim()).find(Boolean)??null}
function cleanTag(tag:unknown){if(typeof tag!=="string")return null;const value=tag.replace(/^[a-z]{2}:/i,"").replace(/-/g," ").trim();return value||null}
function decodeHtml(value:string){return value.replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16)))}
function plainHtml(value:string){return decodeHtml(value.replace(/<script\b[\s\S]*?<\/script>/gi," ").replace(/<style\b[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ")).replace(/\s+/g," ").trim()}
function splitLanguage(value:string|null){if(!value)return{ar:null as string|null,en:null as string|null};return/[\u0600-\u06ff]/.test(value)?{ar:value,en:null}:{ar:null,en:value}}
function tableRows(html:string){const rows:Array<{cells:string[];href:string|null}>=[];for(const match of html.matchAll(/<tr\b[^>]*class=["'][^"']*(?:odd|even)[^"']*["'][^>]*>([\s\S]*?)<\/tr>/gi)){const row=match[1];const cells=[...row.matchAll(/<td\b[^>]*>([\s\S]*?)<\/td>/gi)].map(x=>plainHtml(x[1]));const href=row.match(/href=["']([^"']*details_data[^"']*)["']/i)?.[1]??null;if(cells.length)rows.push({cells,href:href?decodeHtml(href):null})}return rows}
function detailMap(html:string){const out:Record<string,string>={};for(const match of html.matchAll(/<tr[^>]*>\s*<th[^>]*>([\s\S]*?)<\/th>\s*<td[^>]*>([\s\S]*?)<\/td>\s*<\/tr>/gi)){out[plainHtml(match[1]).toLowerCase()]=plainHtml(match[2])}return out}

function masterRowToHit(row:any,barcode:string):MasterHit|null{
  if(!row||validGtin(row.barcode)!==barcode)return null;
  const source=String(row.source??"").toLowerCase();
  const evidenceSource=source==="sfda_cosmetics"?"sfda_cosmetics":"sfda_food";
  if(source!=="sfda_food"&&source!=="sfda_cosmetics")return null;
  const product:GenericProduct={barcode,nameAr:firstText(row.name_ar),nameEn:firstText(row.name_en),brand:firstText(row.brand),quantity:firstText(row.quantity),image:firstText(row.image_url,row.image),source:source==="sfda_cosmetics"?"SFDA Cosmetics":"SFDA Food",sourceRecordId:firstText(row.source_record_id,barcode),sourceUrl:firstText(row.source_url),category:firstText(row.category),manufacturingCountry:firstText(row.manufacturing_country),updatedAt:firstText(row.updated_at)};
  if(!product.nameAr&&!product.nameEn)return null;
  const saudiSignal=firstText(row.saudi_signal)??(source==="sfda_cosmetics"?"sfda_cosmetic_marketing_notification_saudi":"sfda_food_registered_for_saudi_market");
  return{product,evidenceSource,saudiSignal,confidence:1.0};
}

async function fetchSaudiMasterShard(barcode:string):Promise<MasterHit|null>{
  const asset=`gtin-${barcode.slice(0,3).padStart(3,"0")}.jsonl.gz`;
  let response:Response;
  try{response=await fetch(`${MASTER_RELEASE_BASE}/${asset}`,{headers:{"User-Agent":USER_AGENT,Accept:"application/gzip,application/octet-stream,*/*;q=0.5"},redirect:"follow",signal:AbortSignal.timeout(4500)})}catch{return null}
  if(!response.ok||!response.body)return null;
  try{
    const textStream=response.body.pipeThrough(new DecompressionStream("gzip")).pipeThrough(new TextDecoderStream());
    const reader=textStream.getReader();let buffer="";let readChars=0;
    while(true){const{value,done}=await reader.read();if(value){buffer+=value;readChars+=value.length;if(readChars>32_000_000){try{await reader.cancel()}catch{}return null}}let index=buffer.indexOf("\n");while(index>=0){const line=buffer.slice(0,index).trim();buffer=buffer.slice(index+1);if(line){try{const hit=masterRowToHit(JSON.parse(line),barcode);if(hit){try{await reader.cancel()}catch{}return hit}}catch{}}index=buffer.indexOf("\n")}if(done)break}
    const last=buffer.trim();if(last){try{return masterRowToHit(JSON.parse(last),barcode)}catch{}}
  }catch{return null}
  return null;
}

async function sfdaSearchHtml(path:string,barcode:string){const body=new URLSearchParams({Barcode:barcode,op:"Search",form_id:"info_lists_filter_form"}).toString();try{const response=await fetch(`${SFDA_BASE}${path}`,{method:"POST",headers:{"User-Agent":USER_AGENT,Accept:"text/html,application/xhtml+xml,*/*;q=0.8","Accept-Language":"en-US,en;q=0.9,ar-SA;q=0.8","Content-Type":"application/x-www-form-urlencoded",Origin:SFDA_BASE,Referer:`${SFDA_BASE}${path}`},body,redirect:"follow",signal:AbortSignal.timeout(12000)});if(!response.ok)return null;return await response.text()}catch{return null}}
async function fetchSfdaFoodWeb(barcode:string):Promise<GenericProduct|null>{const html=await sfdaSearchHtml("/en/products?pg=1",barcode);if(!html)return null;for(const row of tableRows(html)){if(validGtin(row.cells[0])!==barcode)continue;const ref=row.cells[1]||barcode,brand=row.cells[2]||null,names=splitLanguage(row.cells[3]||null);return{barcode,nameAr:names.ar,nameEn:names.en,brand,quantity:null,image:null,source:"SFDA Food",sourceRecordId:ref,sourceUrl:row.href?new URL(row.href,SFDA_BASE).toString():`${SFDA_BASE}/en/products`}}return null}
async function fetchSfdaCosmeticsWeb(barcode:string):Promise<GenericProduct|null>{const html=await sfdaSearchHtml("/en/cosmetics-list",barcode);if(!html)return null;const rows=tableRows(html).slice(0,10);for(const row of rows){if(!row.href)continue;const detailUrl=new URL(row.href,SFDA_BASE).toString();let detailHtml:string;try{const response=await fetch(detailUrl,{headers:{"User-Agent":USER_AGENT,Accept:"text/html","Accept-Language":"en-US,en;q=0.9,ar-SA;q=0.8"},redirect:"follow",signal:AbortSignal.timeout(10000)});if(!response.ok)continue;detailHtml=await response.text()}catch{continue}const detail=detailMap(detailHtml);if(validGtin(detail["barcode"])!==barcode)continue;const names=splitLanguage(detail["product name"]||row.cells[0]||null);return{barcode,nameAr:names.ar,nameEn:names.en,brand:detail["brand name"]||null,quantity:[detail["package volume"],detail["unit"]].filter(Boolean).join(" ")||null,image:null,source:"SFDA Cosmetics",sourceRecordId:detail["product number"]||barcode,sourceUrl:detailUrl,category:detail["category"]||row.cells[1]||null,manufacturingCountry:detail["country"]||row.cells[2]||null}}return null}

function nutritionNotes(levels:unknown){if(!levels||typeof levels!=="object")return{positive:[] as string[],caution:[] as string[]};const labels:Record<string,{low:string;high:string}>={sugars:{low:"السكريات منخفضة حسب البيانات المفتوحة",high:"السكريات مرتفعة حسب البيانات المفتوحة"},salt:{low:"الملح منخفض حسب البيانات المفتوحة",high:"الملح مرتفع حسب البيانات المفتوحة"},fat:{low:"الدهون منخفضة حسب البيانات المفتوحة",high:"الدهون مرتفعة حسب البيانات المفتوحة"},"saturated-fat":{low:"الدهون المشبعة منخفضة حسب البيانات المفتوحة",high:"الدهون المشبعة مرتفعة حسب البيانات المفتوحة"}};const positive:string[]=[],caution:string[]=[];for(const[key,label]of Object.entries(labels)){const level=String((levels as Record<string,unknown>)[key]??"").toLowerCase();if(level==="low")positive.push(label.low);if(level==="high")caution.push(label.high)}return{positive,caution}}
async function fetchFacts(base:string,barcode:string):Promise<any|null>{const fields=["code","product_name","product_name_en","product_name_ar","brands","quantity","product_quantity","product_quantity_unit","image_front_url","image_url","manufacturing_places","ingredients_text","ingredients_text_en","ingredients_text_ar","allergens_tags","nutrition_grades","nova_group","nutrient_levels","last_modified_t","categories","countries_tags","generic_name","generic_name_en"].join(",");try{const response=await fetch(`${base}${barcode}?fields=${encodeURIComponent(fields)}`,{headers:{"User-Agent":USER_AGENT,Accept:"application/json"},redirect:"follow",signal:AbortSignal.timeout(7000)});if(!response.ok)return null;const raw=await response.json();const product=raw?.product??raw;if(!product||typeof product!=="object")return null;const returned=validGtin(product.code);if(returned&&returned!==barcode)return null;if(raw?.status===0||raw?.status_verbose==="product not found")return null;if(!firstText(product.product_name_ar,product.product_name_en,product.product_name,product.generic_name_en,product.generic_name))return null;return raw}catch{return null}}
function factsToProduct(barcode:string,raw:any,label:string):GenericProduct|null{const product=raw?.product??raw;if(!product||typeof product!=="object")return null;const notes=nutritionNotes(product.nutrient_levels),allergens=Array.isArray(product.allergens_tags)?product.allergens_tags.map(cleanTag).filter(Boolean) as string[]:[],nameAr=firstText(product.product_name_ar),nameEn=firstText(product.product_name_en,product.product_name,product.generic_name_en,product.generic_name);if(!nameAr&&!nameEn)return null;return{barcode,nameAr,nameEn,brand:firstBrand(product.brands),quantity:firstText(product.quantity,product.product_quantity&&product.product_quantity_unit?`${product.product_quantity} ${product.product_quantity_unit}`:null),image:firstText(product.image_front_url,product.image_url),manufacturingPlaces:firstText(product.manufacturing_places),ingredients:firstText(product.ingredients_text_ar,product.ingredients_text_en,product.ingredients_text),allergens,positiveNotes:notes.positive,cautionNotes:notes.caution,nutritionGrade:firstText(product.nutrition_grades),novaGroup:Number.isFinite(Number(product.nova_group))?Number(product.nova_group):null,category:firstText(product.categories),source:label,sourceRecordId:barcode,updatedAt:Number.isFinite(Number(product.last_modified_t))?new Date(Number(product.last_modified_t)*1000).toISOString():null}}
function snapshotHasPrice(payload:any){return!!payload&&(payload.current_price!=null||(Array.isArray(payload.offers)&&payload.offers.length>0))}
async function setAttempt(db:any,barcode:string,status:string,count:number){const now=new Date().toISOString();await db.from("barcode_resolution_attempts").upsert({barcode,last_attempt_at:now,attempt_count:Math.max(1,count),last_status:status,updated_at:now},{onConflict:"barcode"})}
function cooldownFor(status:string|null|undefined){return status?.startsWith("resolved")?RESOLVED_COOLDOWN_MS:MISS_COOLDOWN_MS}
async function writeProduct(db:any,product:GenericProduct,method:string,confidence:number){const{data:canonicalId,error}=await db.rpc("upsert_product_metadata",{p_barcode:product.barcode,p_name_ar:product.nameAr,p_name_en:product.nameEn,p_brand:product.brand,p_image_url:product.image,p_gs1_verified:false,p_identity_key:null,p_variant:null,p_net_content_value:null,p_net_content_unit:null,p_pack_count:1,p_match_confidence:confidence,p_match_method:method});if(error)return null;const info:any={manufacturing_country:product.manufacturingCountry,manufacturing_places:product.manufacturingPlaces,ingredients:product.ingredients,allergens:product.allergens??[],positive_notes:product.positiveNotes??[],caution_notes:product.cautionNotes??[],nutrition_grade:product.nutritionGrade,nova_group:product.novaGroup,category:product.category,data_source:product.source,updated_at:product.updatedAt??new Date().toISOString(),...(product.quantity?{net_content_text:product.quantity}:{})};for(const key of Object.keys(info))if(info[key]===null||info[key]===""||(Array.isArray(info[key])&&!info[key].length))delete info[key];if(Object.keys(info).length>2)await db.rpc("upsert_product_info",{p_barcode:product.barcode,p_product_info:info});return Number(canonicalId)}
async function recordSaudiOfficial(db:any,product:GenericProduct,canonicalId:number,source:string,signal:string){await db.rpc("record_saudi_barcode_evidence",{p_barcode:product.barcode,p_canonical_product_id:canonicalId,p_source:source,p_source_tier:"official_saudi",p_source_record_id:product.sourceRecordId||product.barcode,p_source_url:product.sourceUrl||null,p_confidence:1.0,p_saudi_signal:signal,p_payload:{transport:"saudi_master_or_live"}});await db.rpc("refresh_saudi_master_snapshot",{p_barcode:product.barcode})}
async function createMetadataSnapshot(db:any,product:GenericProduct,confidence:number,method:string){const payload:any={barcode:product.barcode,matched_barcodes:[],name_ar:product.nameAr,name_en:product.nameEn,image_url:product.image,current_price:null,currency:"SAR",retailer:null,price_updated_at:null,min_30d:null,max_30d:null,source_count:1,confidence,offers:[],product_info:{manufacturing_country:product.manufacturingCountry,manufacturing_places:product.manufacturingPlaces,ingredients:product.ingredients,allergens:product.allergens??[],positive_notes:product.positiveNotes??[],caution_notes:product.cautionNotes??[],nutrition_grade:product.nutritionGrade,nova_group:product.novaGroup,data_source:product.source,updated_at:product.updatedAt??new Date().toISOString()},exact_barcode_match:true,headline_match_method:method};for(const key of Object.keys(payload.product_info))if(payload.product_info[key]==null||payload.product_info[key]===""||(Array.isArray(payload.product_info[key])&&!payload.product_info[key].length))delete payload.product_info[key];const payloadHash=await sha(JSON.stringify(payload));await db.from("product_snapshots").upsert({barcode:product.barcode,payload,payload_hash:payloadHash,updated_at:new Date().toISOString()},{onConflict:"barcode"});const{data}=await db.from("product_snapshots").select("payload").eq("barcode",product.barcode).maybeSingle();return data?.payload??payload}

Deno.serve(async(req:Request)=>{
  if(req.method!=="POST")return Response.json({error:"method_not_allowed"},{status:405});
  const projectUrl=Deno.env.get("SUPABASE_URL")??"",key=secretKey();if(!projectUrl||!key)return Response.json({error:"server_config_missing"},{status:503});
  const db=createClient(projectUrl,key,{auth:{persistSession:false,autoRefreshToken:false}});let body:any={};try{body=await req.json()}catch{}
  const barcode=validGtin(body.barcode);if(!barcode)return Response.json({status:"invalid_barcode",payload:null},{status:400});if(restrictedCirculation(barcode))return Response.json({status:"restricted_circulation_barcode",payload:null});
  const{data:existing}=await db.from("product_snapshots").select("payload").eq("barcode",barcode).maybeSingle();if(existing?.payload)return Response.json({status:snapshotHasPrice(existing.payload)?"cached_with_price":"cached_metadata_only",identity_source:"snapshot",payload:existing.payload});
  const{data:attempt}=await db.from("barcode_resolution_attempts").select("last_attempt_at,attempt_count,last_status").eq("barcode",barcode).maybeSingle();if(attempt?.last_attempt_at&&Date.now()-Date.parse(attempt.last_attempt_at)<cooldownFor(attempt.last_status))return Response.json({status:attempt.last_status??"cooldown",payload:null});
  const sinceMinute=new Date(Date.now()-60000).toISOString();const{count:minuteCount}=await db.from("barcode_resolution_attempts").select("barcode",{count:"exact",head:true}).gte("last_attempt_at",sinceMinute);if((minuteCount??0)>=MAX_EXTERNAL_PER_MINUTE)return Response.json({status:"rate_limited",payload:null},{status:429});
  const attemptCount=Number(attempt?.attempt_count??0)+1;await setAttempt(db,barcode,"started",attemptCount);
  const masterHit=await fetchSaudiMasterShard(barcode);if(masterHit){const canonicalId=await writeProduct(db,masterHit.product,"saudi_master_release_exact_gtin",masterHit.confidence);if(canonicalId!=null){await recordSaudiOfficial(db,masterHit.product,canonicalId,masterHit.evidenceSource,masterHit.saudiSignal);const{data}=await db.from("product_snapshots").select("payload").eq("barcode",barcode).maybeSingle();if(data?.payload){const status=snapshotHasPrice(data.payload)?"resolved_with_price":"resolved_metadata_only";await setAttempt(db,barcode,status,attemptCount);return Response.json({status,identity_source:"saudi_master_release",payload:data.payload})}}}
  const sfdaFood=await fetchSfdaFoodWeb(barcode);if(sfdaFood){const canonicalId=await writeProduct(db,sfdaFood,"sfda_food_exact_gtin_web",1.0);if(canonicalId!=null){await recordSaudiOfficial(db,sfdaFood,canonicalId,"sfda_food","sfda_food_registered_for_saudi_market");const{data}=await db.from("product_snapshots").select("payload").eq("barcode",barcode).maybeSingle();if(data?.payload){const status=snapshotHasPrice(data.payload)?"resolved_with_price":"resolved_metadata_only";await setAttempt(db,barcode,status,attemptCount);return Response.json({status,identity_source:"sfda_food_web",payload:data.payload})}}}
  const sfdaCosmetics=await fetchSfdaCosmeticsWeb(barcode);if(sfdaCosmetics){const canonicalId=await writeProduct(db,sfdaCosmetics,"sfda_cosmetics_exact_gtin_web",1.0);if(canonicalId!=null){await recordSaudiOfficial(db,sfdaCosmetics,canonicalId,"sfda_cosmetics","sfda_cosmetic_marketing_notification_saudi");const{data}=await db.from("product_snapshots").select("payload").eq("barcode",barcode).maybeSingle();if(data?.payload){const status=snapshotHasPrice(data.payload)?"resolved_with_price":"resolved_metadata_only";await setAttempt(db,barcode,status,attemptCount);return Response.json({status,identity_source:"sfda_cosmetics_web",payload:data.payload})}}}
  for(const source of FACTS_SOURCES){const raw=await fetchFacts(source.base,barcode);if(!raw)continue;const product=factsToProduct(barcode,raw,source.label);if(!product)continue;const canonicalId=await writeProduct(db,product,`${source.id}_exact_gtin`,0.84);if(canonicalId==null)continue;const payload=await createMetadataSnapshot(db,product,0.84,"open_source_exact_gtin");const status=snapshotHasPrice(payload)?"resolved_with_price":"resolved_metadata_only";await setAttempt(db,barcode,status,attemptCount);return Response.json({status,identity_source:source.id,payload})}
  await setAttempt(db,barcode,"not_found",attemptCount);return Response.json({status:"not_found",identity_source:null,payload:null});
});
