import { createClient } from "npm:@supabase/supabase-js@2";

const OFF_URL = "https://world.openfoodfacts.org/api/v3/product/";
const SFDA_SEARCH_URL = "https://api.sfda.gov.sa:9001/v2/FIRS/food/search";
// Published by SFDA on its public registered-food-products service page.
const SFDA_PUBLIC_API_KEY = "dZRGUbnQeaDndOXk9hX9GFCxXzCSraEz";
const USER_AGENT = "MoqarinAlasaar/2.1 (Saudi barcode resolution; GitHub Malik05255/super_-market)";
const enc = new TextEncoder();
const COOLDOWN_MS = 12 * 60 * 60 * 1000;
const MAX_EXTERNAL_PER_MINUTE = 10;

const STOP = new Set(["can","cans","bottle","bottles","pet","pack","packs","piece","pieces","pc","pcs","ml","cl","ltr","liter","litre","g","gm","gram","kg","علبة","علب","عبوة","عبوات","زجاجة","زجاجات","حبة","حبات","مل","لتر","جرام","غرام","كيلو","كجم"]);
const VAR:Record<string,string[]> = {zero:["zero","زيرو","صفر"],diet:["diet","دايت","حمية"],light:["light","لايت","خفيف"],original:["original","regular","classic","اصلي","أصلي","عادي","كلاسيك"],cherry:["cherry","كرز"],vanilla:["vanilla","فانيلا"],lemon:["lemon","ليمون"],lime:["lime","لايم"]};
const SIZES:Array<[RegExp,string,number]> = [
  [/\b(\d+(?:[.,]\d+)?)\s*(?:ml|مل|مليلتر|millilit(?:er|re)s?)\b/i,"ml",1],
  [/\b(\d+(?:[.,]\d+)?)\s*(?:cl|centilitre|centiliter)\b/i,"ml",10],
  [/\b(\d+(?:[.,]\d+)?)\s*(?:l|ltr|liter|litre|لتر)\b/i,"ml",1000],
  [/\b(\d+(?:[.,]\d+)?)\s*(?:g|gm|gram|جرام|غرام)\b/i,"g",1],
  [/\b(\d+(?:[.,]\d+)?)\s*(?:kg|kilogram|كيلو|كجم)\b/i,"g",1000]
];
const PACKS = [/(?:^|\D)(\d{1,3})\s*[x×]\s*/i,/(?:pack|pk|عبوة|عبوات|حبة|حبات)\s*(?:of\s*)?(\d{1,3})(?!\d)/i,/(?:^|\D)(\d{1,3})\s*(?:pack|pk|pcs|pieces|حبة|حبات|عبوة|عبوات)(?!\w)/i];

type Identity = {key:string|null;variant:string|null;sizeValue:number|null;sizeUnit:string|null;packCount:number;confidence:number;method:string};

type SfdaProduct = {
  barcode:string;
  nameAr:string|null;
  nameEn:string|null;
  brand:string|null;
  quantity:string|null;
  image:string|null;
  countryOfOrigin:string|null;
  ingredients:string|null;
  warnings:string|null;
};

function secretKey(){const modern=Deno.env.get("SUPABASE_SECRET_KEYS");if(modern){try{const parsed=JSON.parse(modern);if(parsed?.default)return String(parsed.default)}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??""}
function validGtin(value:unknown):string|null{if(value==null)return null;const d=String(value).replace(/\D+/g,"");if(![8,12,13,14].includes(d.length))return null;let total=0;[...d.slice(0,-1)].reverse().forEach((x,i)=>total+=Number(x)*(i%2===0?3:1));return Number(d.at(-1))===(10-total%10)%10?d:null}
function norm(value:string|null|undefined){return(value??"").normalize("NFKC").toLowerCase().trim().replace(/[أإآ]/g,"ا").replace(/ة/g,"ه").replace(/ى/g,"ي").replace(/[^0-9a-z\u0600-\u06ff]+/gi," ").replace(/\s+/g," ").trim()}
async function sha(value:string){const h=await crypto.subtle.digest("SHA-256",enc.encode(value));return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function identity(name:string|null,brand:string|null,quantity:string|null,method="external_identity_v2"):Promise<Identity>{const identityName=[name,quantity].filter(Boolean).join(" "),source=[identityName,brand].filter(Boolean).join(" "),nb=norm(brand);let sv:number|null=null,su:string|null=null;for(const[p,u,m]of SIZES){const x=source.match(p);if(x){const n=Number(x[1].replace(",","."))*m;if(n>0&&n<=100000){sv=Math.round(n*1000)/1000;su=u;break}}}let pc=1;for(const p of PACKS){const x=source.match(p);if(x){const n=Number(x[1]);if(n>=1&&n<=100){pc=n;break}}}const tokens=new Set(norm(source).split(" ").filter(Boolean)),variants:string[]=[];for(const[k,words]of Object.entries(VAR))if(words.some(w=>tokens.has(norm(w))))variants.push(k);const variant=variants.length?[...new Set(variants)].sort().join("+"):null;if(!nb||sv===null||!su)return{key:null,variant,sizeValue:sv,sizeUnit:su,packCount:pc,confidence:0,method:"isolated_missing_identity_fields"};let stripped=identityName;for(const[p]of SIZES)stripped=stripped.replace(p," ");for(const p of PACKS)stripped=stripped.replace(p," ");const brandTokens=new Set(nb.split(" ")),variantTokens=new Set(Object.values(VAR).flat().map(norm)),family=[...new Set(norm(stripped).split(" ").filter(t=>t.length>1&&!/^\d+$/.test(t)&&!STOP.has(t)&&!brandTokens.has(t)&&!variantTokens.has(t)))].sort().slice(0,6);if(!family.length&&!variant)return{key:null,variant,sizeValue:sv,sizeUnit:su,packCount:pc,confidence:0,method:"isolated_ambiguous_family"};const raw=[nb,variant??"standard",`${String(sv)}:${su}`,String(pc),family.join(",")].join("|"),digest=(await sha(raw)).slice(0,32);return{key:`v2:${digest}`,variant,sizeValue:sv,sizeUnit:su,packCount:pc,confidence:variant?0.96:0.92,method}}
function firstText(...values:unknown[]){for(const value of values){if(typeof value==="string"&&value.trim())return value.trim();if(typeof value==="number"&&Number.isFinite(value))return String(value)}return null}
function firstBrand(value:unknown){if(typeof value!=="string")return null;return value.split(",").map(x=>x.trim()).find(Boolean)??null}
function cleanTag(tag:unknown){if(typeof tag!=="string")return null;const v=tag.replace(/^[a-z]{2}:/i,"").replace(/-/g," ").trim();return v||null}
function nutritionNotes(levels:unknown){if(!levels||typeof levels!=="object")return{positive:[] as string[],caution:[] as string[]};const labels:Record<string,{low:string;high:string}>={sugars:{low:"السكريات منخفضة حسب بيانات Open Food Facts",high:"السكريات مرتفعة حسب بيانات Open Food Facts"},salt:{low:"الملح منخفض حسب بيانات Open Food Facts",high:"الملح مرتفع حسب بيانات Open Food Facts"},fat:{low:"الدهون منخفضة حسب بيانات Open Food Facts",high:"الدهون مرتفعة حسب بيانات Open Food Facts"},"saturated-fat":{low:"الدهون المشبعة منخفضة حسب بيانات Open Food Facts",high:"الدهون المشبعة مرتفعة حسب بيانات Open Food Facts"}};const positive:string[]=[],caution:string[]=[];for(const[key,label]of Object.entries(labels)){const level=String((levels as Record<string,unknown>)[key]??"").toLowerCase();if(level==="low")positive.push(label.low);if(level==="high")caution.push(label.high)}return{positive,caution}}
async function setAttempt(db:any,barcode:string,status:string,count:number){const now=new Date().toISOString();await db.from("barcode_resolution_attempts").upsert({barcode,last_attempt_at:now,attempt_count:Math.max(1,count),last_status:status,updated_at:now},{onConflict:"barcode"})}
function snapshotHasPrice(payload:any){return !!payload&&(payload.current_price!=null||(Array.isArray(payload.offers)&&payload.offers.length>0))}

function walkObjects(value:unknown,out:Record<string,unknown>[]){if(Array.isArray(value)){for(const child of value)walkObjects(child,out);return}if(!value||typeof value!=="object")return;const obj=value as Record<string,unknown>;out.push(obj);for(const child of Object.values(obj))if(child&&typeof child==="object")walkObjects(child,out)}
function pick(obj:Record<string,unknown>,...keys:string[]){for(const key of keys){if(obj[key]!=null&&String(obj[key]).trim())return obj[key]}return null}
function findSfdaExact(raw:unknown,barcode:string):Record<string,unknown>|null{const objects:Record<string,unknown>[]=[];walkObjects(raw,objects);for(const obj of objects){const candidate=validGtin(pick(obj,"barcode","Barcode","barCode","ean","EAN","gtin","GTIN"));if(candidate===barcode)return obj}return null}
async function fetchSfda(barcode:string):Promise<SfdaProduct|null>{const url=new URL(SFDA_SEARCH_URL);url.searchParams.set("apikey",SFDA_PUBLIC_API_KEY);url.searchParams.set("Barcode",barcode);let response:Response;try{response=await fetch(url,{headers:{"User-Agent":USER_AGENT,Accept:"application/json"},redirect:"follow",signal:AbortSignal.timeout(6000)})}catch{return null}if(!response.ok)return null;let raw:unknown;try{raw=await response.json()}catch{return null}const obj=findSfdaExact(raw,barcode);if(!obj)return null;const nameAr=firstText(pick(obj,"tradeNameAr","TradeNameAr","itemDescriptionAr","ItemDescriptionAr"));const nameEn=firstText(pick(obj,"tradeName","tradeNameEn","TradeName","TradeNameEn","itemDescription","itemDescriptionEn","ItemDescription","ItemDescriptionEn"));const brand=firstText(pick(obj,"brandName","brandNameEn","brandNameAr","BrandName","BrandNameEn","BrandNameAr"));const weight=firstText(pick(obj,"itemWeight","ItemWeight","weight","Weight"));const unit=firstText(pick(obj,"unitNameEn","unitNameAr","UnitNameEn","UnitNameAr","unit","Unit"));const quantity=[weight,unit].filter(Boolean).join(" ")||null;return{barcode,nameAr,nameEn,brand,quantity,image:firstText(pick(obj,"image","imageUrl","Image","ImageUrl")),countryOfOrigin:firstText(pick(obj,"countryOfOriginEn","countryOfOriginAr","countryOfOrigin","CountryOfOriginEn","CountryOfOriginAr","CountryOfOrigin")),ingredients:firstText(pick(obj,"ingredientsAr","ingredientsEn","ingredients","IngredientsAr","IngredientsEn","Ingredients")),warnings:firstText(pick(obj,"warningsAr","warningsEn","warnings","WarningsAr","WarningsEn","Warnings"))}}
async function writeSfda(db:any,product:SfdaProduct){const name=product.nameAr??product.nameEn,id=await identity(name,product.brand,product.quantity,"sfda_registered_food_identity_v2");const {error}=await db.rpc("upsert_product_metadata",{p_barcode:product.barcode,p_name_ar:product.nameAr,p_name_en:product.nameEn,p_brand:product.brand,p_image_url:product.image,p_gs1_verified:false,p_identity_key:id.key,p_variant:id.variant,p_net_content_value:id.sizeValue,p_net_content_unit:id.sizeUnit,p_pack_count:id.packCount,p_match_confidence:id.confidence,p_match_method:id.method});if(error)return false;const info:any={manufacturing_country:product.countryOfOrigin,ingredients:product.ingredients,caution_notes:product.warnings?[product.warnings]:[],data_source:"Saudi Food and Drug Authority (SFDA)",updated_at:new Date().toISOString()};for(const k of Object.keys(info))if(info[k]===null||info[k]===""||(Array.isArray(info[k])&&!info[k].length))delete info[k];if(Object.keys(info).length>2)await db.rpc("upsert_product_info",{p_barcode:product.barcode,p_product_info:info});return true}

async function fetchOff(barcode:string){const fields=["code","product_name","product_name_en","product_name_ar","brands","quantity","product_quantity","product_quantity_unit","image_front_url","image_url","manufacturing_places","ingredients_text","ingredients_text_en","ingredients_text_ar","allergens_tags","nutrition_grades","nova_group","nutrient_levels","last_modified_t"].join(",");let response:Response;try{response=await fetch(`${OFF_URL}${barcode}?fields=${encodeURIComponent(fields)}`,{headers:{"User-Agent":USER_AGENT,Accept:"application/json"},redirect:"follow",signal:AbortSignal.timeout(8000)})}catch{return null}if(!response.ok)return null;try{return await response.json()}catch{return null}}
async function writeOff(db:any,barcode:string,raw:any){const product=raw?.product??raw;if(!product||typeof product!=="object")return false;const returnedCode=validGtin(product.code);if(returnedCode&&returnedCode!==barcode)return false;const nameAr=firstText(product.product_name_ar),nameEn=firstText(product.product_name_en,product.product_name),name=nameAr??nameEn,brand=firstBrand(product.brands),quantity=firstText(product.quantity,product.product_quantity&&product.product_quantity_unit?`${product.product_quantity} ${product.product_quantity_unit}`:null),id=await identity(name,brand,quantity,"open_food_facts_identity_v2"),image=firstText(product.image_front_url,product.image_url);const {error}=await db.rpc("upsert_product_metadata",{p_barcode:barcode,p_name_ar:nameAr,p_name_en:nameEn,p_brand:brand,p_image_url:image,p_gs1_verified:false,p_identity_key:id.key,p_variant:id.variant,p_net_content_value:id.sizeValue,p_net_content_unit:id.sizeUnit,p_pack_count:id.packCount,p_match_confidence:id.confidence,p_match_method:id.method});if(error)return false;const notes=nutritionNotes(product.nutrient_levels),allergens=Array.isArray(product.allergens_tags)?product.allergens_tags.map(cleanTag).filter(Boolean):[],info:any={manufacturing_places:firstText(product.manufacturing_places),ingredients:firstText(product.ingredients_text_ar,product.ingredients_text_en,product.ingredients_text),allergens,positive_notes:notes.positive,caution_notes:notes.caution,nutrition_grade:firstText(product.nutrition_grades),nova_group:Number.isFinite(Number(product.nova_group))?Number(product.nova_group):null,data_source:"Open Food Facts",updated_at:Number.isFinite(Number(product.last_modified_t))?new Date(Number(product.last_modified_t)*1000).toISOString():new Date().toISOString()};for(const k of Object.keys(info))if(info[k]===null||info[k]===""||(Array.isArray(info[k])&&!info[k].length))delete info[k];if(Object.keys(info).length>2)await db.rpc("upsert_product_info",{p_barcode:barcode,p_product_info:info});return true}

Deno.serve(async(req:Request)=>{if(req.method!=="POST")return Response.json({error:"method_not_allowed"},{status:405});const projectUrl=Deno.env.get("SUPABASE_URL")??"",key=secretKey();if(!projectUrl||!key)return Response.json({error:"server_config_missing"},{status:503});const db=createClient(projectUrl,key,{auth:{persistSession:false,autoRefreshToken:false}});let body:any={};try{body=await req.json()}catch{}const barcode=validGtin(body.barcode);if(!barcode)return Response.json({status:"invalid_barcode",payload:null},{status:400});
const {data:existing}=await db.from("product_snapshots").select("payload").eq("barcode",barcode).maybeSingle();if(existing?.payload)return Response.json({status:"found",payload:existing.payload});
const {data:attempt}=await db.from("barcode_resolution_attempts").select("last_attempt_at,attempt_count,last_status").eq("barcode",barcode).maybeSingle();if(attempt?.last_attempt_at&&Date.now()-Date.parse(attempt.last_attempt_at)<COOLDOWN_MS)return Response.json({status:attempt.last_status??"cooldown",payload:null});
const since=new Date(Date.now()-60_000).toISOString();const {count}=await db.from("barcode_resolution_attempts").select("barcode",{count:"exact",head:true}).gte("last_attempt_at",since);if((count??0)>=MAX_EXTERNAL_PER_MINUTE)return Response.json({status:"rate_limited",payload:null},{status:429});
const attemptCount=Number(attempt?.attempt_count??0)+1;await setAttempt(db,barcode,"started",attemptCount);

// Saudi-authoritative identity path first. SFDA is never treated as a supermarket-price source.
const sfda=await fetchSfda(barcode);if(sfda&&await writeSfda(db,sfda)){await db.rpc("rebuild_product_snapshots");const {data:afterSfda}=await db.from("product_snapshots").select("payload").eq("barcode",barcode).maybeSingle();if(snapshotHasPrice(afterSfda?.payload)){await setAttempt(db,barcode,"resolved_with_price_sfda",attemptCount);return Response.json({status:"resolved_with_price",identity_source:"sfda",payload:afterSfda.payload})}}

// Open Food Facts remains a metadata/nutrition fallback. It never supplies retailer prices.
const off=await fetchOff(barcode);if(off)await writeOff(db,barcode,off);
await db.rpc("rebuild_product_snapshots");const {data:resolved}=await db.from("product_snapshots").select("payload").eq("barcode",barcode).maybeSingle();const payload=resolved?.payload??null,status=snapshotHasPrice(payload)?"resolved_with_price":payload?"resolved_metadata_only":sfda?"sfda_identity_unmatched":"not_found";await setAttempt(db,barcode,status,attemptCount);return Response.json({status,identity_source:sfda?"sfda":off?"open_food_facts":null,payload});});