import { createClient } from "npm:@supabase/supabase-js@2";

const UA = "MoqarinAlasaarSaudiMaster/1.1 (+free Saudi product identity sync; SFDA + Open Facts)";
const enc = new TextEncoder();
const SFDA_BASE = "https://www.sfda.gov.sa";

type SourceDef = {
  kind: "sfda_food_html" | "sfda_cosmetics_html" | "open_facts";
  url: string;
  tier: "official_saudi" | "open_global";
  signal: string;
  pageSize: number;
  sourceUrl: string;
  startPage: number;
};

const SOURCES: Record<string, SourceDef> = {
  sfda_food: { kind:"sfda_food_html", url:`${SFDA_BASE}/en/products`, tier:"official_saudi", signal:"sfda_food_registered_for_saudi_market", pageSize:10, sourceUrl:`${SFDA_BASE}/en/products`, startPage:0 },
  sfda_cosmetics: { kind:"sfda_cosmetics_html", url:`${SFDA_BASE}/en/cosmetics-list`, tier:"official_saudi", signal:"sfda_cosmetic_marketing_notification_saudi", pageSize:10, sourceUrl:`${SFDA_BASE}/en/cosmetics-list`, startPage:0 },
  open_food_facts_saudi: { kind:"open_facts", url:"https://world.openfoodfacts.org/api/v2/search", tier:"open_global", signal:"open_facts_country_tag_saudi_arabia", pageSize:100, sourceUrl:"https://world.openfoodfacts.org/", startPage:1 },
  open_products_facts_saudi: { kind:"open_facts", url:"https://world.openproductsfacts.org/api/v2/search", tier:"open_global", signal:"open_facts_country_tag_saudi_arabia", pageSize:100, sourceUrl:"https://world.openproductsfacts.org/", startPage:1 },
  open_beauty_facts_saudi: { kind:"open_facts", url:"https://world.openbeautyfacts.org/api/v2/search", tier:"open_global", signal:"open_facts_country_tag_saudi_arabia", pageSize:100, sourceUrl:"https://world.openbeautyfacts.org/", startPage:1 },
  open_pet_food_facts_saudi: { kind:"open_facts", url:"https://world.openpetfoodfacts.org/api/v2/search", tier:"open_global", signal:"open_facts_country_tag_saudi_arabia", pageSize:100, sourceUrl:"https://world.openpetfoodfacts.org/", startPage:1 },
};

function secretKey(){const m=Deno.env.get("SUPABASE_SECRET_KEYS");if(m){try{const p=JSON.parse(m);if(p?.default)return String(p.default)}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??""}
async function sha(v:string){const h=await crypto.subtle.digest("SHA-256",enc.encode(v));return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function asciiDigits(v:unknown){const ar="٠١٢٣٤٥٦٧٨٩",fa="۰۱۲۳۴۵۶۷۸۹";return String(v??"").replace(/[٠-٩]/g,c=>String(ar.indexOf(c))).replace(/[۰-۹]/g,c=>String(fa.indexOf(c))).replace(/\D+/g,"")}
function validGtin(v:unknown):string|null{const d=asciiDigits(v);if(![8,12,13,14].includes(d.length))return null;let t=0;[...d.slice(0,-1)].reverse().forEach((x,i)=>t+=Number(x)*(i%2===0?3:1));return Number(d.at(-1))===(10-t%10)%10?d:null}
function decode(s:string){return s.replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16)))}
function plain(h:string){return decode(h.replace(/<script\b[\s\S]*?<\/script>/gi," ").replace(/<style\b[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ")).replace(/\s+/g," ").trim()}
function text(v:unknown){if(typeof v==="string"&&v.trim())return v.trim();if(typeof v==="number"&&Number.isFinite(v))return String(v);return null}
function splitLang(v:string|null){if(!v)return{ar:null,en:null};return/[\u0600-\u06ff]/.test(v)?{ar:v,en:null}:{ar:null,en:v}}
async function fetchText(url:string){const r=await fetch(url,{headers:{"User-Agent":UA,Accept:"text/html,application/xhtml+xml,*/*;q=0.8","Accept-Language":"ar-SA,ar;q=0.9,en;q=0.8"},redirect:"follow",signal:AbortSignal.timeout(20000)});const body=await r.text();if(!r.ok)throw new Error(`HTTP ${r.status}: ${body.slice(0,200)}`);return body}
async function fetchJson(url:string){const r=await fetch(url,{headers:{"User-Agent":UA,Accept:"application/json"},redirect:"follow",signal:AbortSignal.timeout(20000)});const body=await r.text();if(!r.ok)throw new Error(`HTTP ${r.status}: ${body.slice(0,200)}`);try{return JSON.parse(body)}catch{throw new Error(`Non-JSON: ${body.slice(0,200)}`)}}
function tableRows(html:string){const out:Array<{cells:string[],href:string|null}>=[];for(const m of html.matchAll(/<tr\b[^>]*class=["'][^"']*(?:odd|even)[^"']*["'][^>]*>([\s\S]*?)<\/tr>/gi)){const row=m[1],cells=[...row.matchAll(/<td\b[^>]*>([\s\S]*?)<\/td>/gi)].map(x=>plain(x[1]));const href=row.match(/href=["']([^"']*details_data[^"']*)["']/i)?.[1];if(cells.length)out.push({cells,href:href?decode(href):null})}return out}
function lastHtmlPage(html:string){const all=[...html.matchAll(/[?&](?:amp;)?page=(\d+)[^"']*["'][^>]*title=["']Go to last page["']/gi)].map(m=>Number(m[1])).filter(Number.isFinite);return all.length?Math.max(...all):null}
function detailMap(html:string){const out:Record<string,string>={};for(const m of html.matchAll(/<tr[^>]*>\s*<th[^>]*>([\s\S]*?)<\/th>\s*<td[^>]*>([\s\S]*?)<\/td>\s*<\/tr>/gi)){out[plain(m[1]).toLowerCase()]=plain(m[2])}return out}
function foodRow(row:{cells:string[],href:string|null},def:SourceDef){if(row.cells.length<4)return null;const barcode=validGtin(row.cells[0]);if(!barcode)return null;const ref=row.cells[1]||barcode,brand=row.cells[2]||null,n=splitLang(row.cells[3]||null);return{barcode,name_ar:n.ar,name_en:n.en,brand,image_url:null,confidence:1,source_record_id:ref,source_url:def.sourceUrl,product_info:{data_source:"SFDA Food",updated_at:new Date().toISOString()},evidence_payload:{reference_number:ref}}}
async function cosmeticRow(row:{cells:string[],href:string|null},def:SourceDef){if(!row.href)return null;const url=new URL(row.href,SFDA_BASE).toString();const html=await fetchText(url),d=detailMap(html);const barcode=validGtin(d["barcode"]);if(!barcode)return null;const raw=d["product name"]||row.cells[0]||null,n=splitLang(raw),ref=d["product number"]||barcode,brand=d["brand name"]||null,country=d["country"]||null,category=d["category"]||row.cells[1]||null,vol=d["package volume"]||null,unit=d["unit"]||null;return{barcode,name_ar:n.ar,name_en:n.en,brand,image_url:null,confidence:1,source_record_id:ref,source_url:url,product_info:{...(country?{manufacturing_country:country}:{}),...(category?{category}:{}),...(vol?{net_content_text:[vol,unit].filter(Boolean).join(" ")}:{}),data_source:"SFDA Cosmetics",updated_at:new Date().toISOString()},evidence_payload:{cosmetic_number:ref,status:d["status"]||null}}}
function arrayFrom(raw:any){if(Array.isArray(raw))return raw;if(!raw||typeof raw!=="object")return[];for(const k of["products","data","items","results","records","list","result"]){if(Array.isArray(raw[k]))return raw[k];if(raw[k]&&typeof raw[k]==="object")for(const n of["products","data","items","results","records","list","result"])if(Array.isArray(raw[k][n]))return raw[k][n]}return[]}
function totalFrom(raw:any):number|null{if(!raw||typeof raw!=="object")return null;for(const k of["count","total","totalCount","total_count","recordsTotal"]){const n=Number(raw[k]);if(Number.isFinite(n)&&n>=0)return n}return null}
function ci(o:Record<string,unknown>,...keys:string[]){const map=new Map(Object.entries(o).map(([k,v])=>[k.toLowerCase(),v]));for(const k of keys){const v=map.get(k.toLowerCase());if(v!=null&&String(v).trim())return v}return null}
function openFactsRow(o:Record<string,unknown>,def:SourceDef){const barcode=validGtin(ci(o,"code","barcode","gtin"));if(!barcode)return null;const ar=text(ci(o,"product_name_ar")),en=text(ci(o,"product_name_en","product_name"));if(!ar&&!en)return null;const modified=Number(ci(o,"last_modified_t")),category=text(ci(o,"categories")),qty=text(ci(o,"quantity"));return{barcode,name_ar:ar,name_en:en,brand:text(ci(o,"brands")),image_url:text(ci(o,"image_front_url","image_url")),confidence:.84,source_record_id:barcode,source_url:def.sourceUrl,product_info:{...(category?{category}:{}),...(qty?{net_content_text:qty}:{}),data_source:def.sourceUrl,...(Number.isFinite(modified)?{updated_at:new Date(modified*1000).toISOString()}: {})},evidence_payload:{countries_tags:ci(o,"countries_tags")??[]}}}
async function sourcePage(source:string,def:SourceDef,page:number,probe:boolean){if(def.kind==="sfda_food_html"){const url=`${def.url}?page=${page}`,html=await fetchText(url),rows=tableRows(html),normalized=rows.map(r=>foodRow(r,def)).filter(Boolean);return{normalized,rawCount:rows.length,totalPages:lastHtmlPage(html)!=null?lastHtmlPage(html)!+1:null,url,sample:probe?rows.slice(0,2):undefined}}if(def.kind==="sfda_cosmetics_html"){const url=`${def.url}?page=${page}`,html=await fetchText(url),rows=tableRows(html);const normalized:any[]=[];for(let i=0;i<rows.length;i+=5){const part=rows.slice(i,i+5),values=await Promise.all(part.map(r=>cosmeticRow(r,def).catch(()=>null)));normalized.push(...values.filter(Boolean))}return{normalized,rawCount:rows.length,totalPages:lastHtmlPage(html)!=null?lastHtmlPage(html)!+1:null,url,sample:probe?rows.slice(0,2):undefined}}const u=new URL(def.url);u.searchParams.set("countries_tags_en","saudi-arabia");u.searchParams.set("page",String(page));u.searchParams.set("page_size",String(def.pageSize));u.searchParams.set("sort_by","last_modified_t");u.searchParams.set("fields","code,product_name,product_name_ar,product_name_en,brands,quantity,image_front_url,image_url,categories,countries_tags,last_modified_t");const raw=await fetchJson(u.toString()),records=arrayFrom(raw),normalized=records.filter(x=>x&&typeof x==="object").map(x=>openFactsRow(x,def)).filter(Boolean);const total=totalFrom(raw);return{normalized,rawCount:records.length,totalPages:total!=null?Math.ceil(total/def.pageSize):null,url:u.toString(),sample:probe?normalized.slice(0,2):undefined}}

Deno.serve(async(req:Request)=>{if(req.method!=="POST")return Response.json({error:"method_not_allowed"},{status:405});const projectUrl=Deno.env.get("SUPABASE_URL")??"",key=secretKey();if(!projectUrl||!key)return Response.json({error:"server_config_missing"},{status:503});const db=createClient(projectUrl,key,{auth:{persistSession:false,autoRefreshToken:false}}),token=req.headers.get("x-ingest-token")??"",{data:ctl}=await db.from("ingest_control").select("value").eq("key","cron_token_sha256").maybeSingle();if(!ctl?.value||(await sha(token))!==ctl.value)return Response.json({error:"unauthorized"},{status:401});let body:any={};try{body=await req.json()}catch{}const requested=body.source?[String(body.source)]:Object.keys(SOURCES),unknown=requested.filter(s=>!SOURCES[s]);if(unknown.length)return Response.json({error:"unknown_source",sources:unknown},{status:400});const maxPages=Math.max(1,Math.min(Number(body.max_pages??1)||1,40)),probe=body.probe===true,started=Date.now(),output:any[]=[];
for(const source of requested){if(Date.now()-started>108000)break;const def=SOURCES[source],{data:state}=await db.from("saudi_master_sync_state").select("*").eq("source",source).maybeSingle();let page=Math.max(def.startPage,Number(state?.cursor??def.startPage)),seen=0,imported=0,rejected=0,errors=0,status="ok",lastError:string|null=null,lastFingerprint=String(state?.metadata?.last_fingerprint??""),totalPages:number|null=null;const pages:any[]=[];for(let n=0;n<maxPages;n++){if(Date.now()-started>108000){status="time_budget";break}try{const result=await sourcePage(source,def,page,probe);totalPages=result.totalPages;const normalized=[...new Map((result.normalized as any[]).map(x=>[`${x.barcode}|${x.source_record_id}`,x])).values()],fingerprint=normalized.length?`${normalized[0].barcode}|${normalized.at(-1)?.barcode}|${result.rawCount}`:`empty|${page}`;if(probe){pages.push({page,url:result.url,raw:result.rawCount,normalized:normalized.length,total_pages:totalPages,sample:result.sample});page++;continue}if(page>def.startPage&&fingerprint===lastFingerprint&&result.rawCount>0){status="pagination_repeated";break}let batch:any={imported:0,rejected:0,errors:0};if(normalized.length){const {data,error}=await db.rpc("ingest_saudi_master_batch",{p_source:source,p_source_tier:def.tier,p_saudi_signal:def.signal,p_rows:normalized});if(error)throw error;batch=data??batch}seen+=result.rawCount;imported+=Number(batch.imported??0);rejected+=(result.rawCount-normalized.length)+Number(batch.rejected??0);errors+=Number(batch.errors??0);pages.push({page,raw:result.rawCount,normalized:normalized.length,imported:Number(batch.imported??0),errors:Number(batch.errors??0),total_pages:totalPages});lastFingerprint=fingerprint;const next=page+1,finished=result.rawCount===0||(totalPages!=null&&next>=totalPages);page=finished?def.startPage:next;if(finished){status="cycle_complete";break}}catch(e){status="error";lastError=e instanceof Error?e.message:String(e);break}}if(!probe)await db.from("saudi_master_sync_state").upsert({source,cursor:page,status,last_attempt_at:new Date().toISOString(),...(status!=="error"?{last_success_at:new Date().toISOString()}:{}),items_seen:Number(state?.items_seen??0)+seen,items_imported:Number(state?.items_imported??0)+imported,last_error:lastError,metadata:{...(state?.metadata??{}),last_fingerprint:lastFingerprint,total_pages:totalPages,last_pages:pages.slice(-5)},updated_at:new Date().toISOString()},{onConflict:"source"});output.push({source,status,cursor_next:page,seen,imported,rejected,errors,total_pages:totalPages,pages,error:lastError})}
return Response.json({status:"ok",probe,elapsed_ms:Date.now()-started,sources:output})});
