-- Retailer price evidence that can be verified by product identity even when the
-- retailer page does not expose a GTIN. No barcode is fabricated for these offers.

create table if not exists public.retailer_identity_sources (
    id bigint generated by default as identity primary key,
    canonical_product_id bigint not null references public.canonical_products(id) on delete cascade,
    retailer_id bigint not null references public.retailers(id) on delete cascade,
    identity_key text not null,
    source_url text not null,
    branch_key text not null default 'online',
    active boolean not null default true,
    last_checked_at timestamptz,
    last_error text,
    created_at timestamptz not null default now(),
    unique (retailer_id, source_url)
);

create index if not exists retailer_identity_sources_identity_idx
    on public.retailer_identity_sources(identity_key);
create index if not exists retailer_identity_sources_refresh_idx
    on public.retailer_identity_sources(active, retailer_id, last_checked_at);

create table if not exists public.identity_price_periods (
    id bigint generated by default as identity primary key,
    canonical_product_id bigint not null references public.canonical_products(id) on delete cascade,
    retailer_id bigint not null references public.retailers(id) on delete cascade,
    branch_key text not null default 'online',
    price numeric(12,2) not null check (price > 0),
    currency text not null default 'SAR',
    source_url text,
    valid_from timestamptz not null,
    valid_to timestamptz,
    last_seen_at timestamptz not null,
    created_at timestamptz not null default now()
);

create index if not exists identity_price_periods_canonical_time_idx
    on public.identity_price_periods(canonical_product_id, last_seen_at desc);
create index if not exists identity_price_periods_retailer_time_idx
    on public.identity_price_periods(retailer_id, last_seen_at desc);
create unique index if not exists identity_price_periods_one_open_idx
    on public.identity_price_periods(canonical_product_id, retailer_id, branch_key)
    where valid_to is null;

alter table public.retailer_identity_sources enable row level security;
alter table public.identity_price_periods enable row level security;
revoke all on table public.retailer_identity_sources from anon, authenticated;
revoke all on table public.identity_price_periods from anon, authenticated;
grant select, insert, update, delete on table public.retailer_identity_sources to service_role;
grant select, insert, update, delete on table public.identity_price_periods to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.record_identity_price(
    p_identity_key text,
    p_name_ar text,
    p_name_en text,
    p_brand text,
    p_variant text,
    p_net_content_value numeric,
    p_net_content_unit text,
    p_pack_count integer,
    p_image_url text,
    p_retailer_slug text,
    p_branch_key text,
    p_price numeric,
    p_currency text default 'SAR',
    p_source_url text default null,
    p_observed_at timestamptz default now()
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_identity_key text := nullif(trim(coalesce(p_identity_key, '')), '');
    v_retailer_id bigint;
    v_canonical_id bigint;
    v_current public.identity_price_periods%rowtype;
begin
    if v_identity_key is null then
        raise exception 'identity_key is required';
    end if;
    if p_price is null or p_price <= 0 then
        raise exception 'positive price is required';
    end if;

    select id into v_retailer_id
    from public.retailers
    where slug = p_retailer_slug and active = true;
    if v_retailer_id is null then
        raise exception 'Unknown or inactive retailer: %', p_retailer_slug;
    end if;

    insert into public.canonical_products (
        canonical_name_ar, canonical_name_en, brand, variant,
        net_content_value, net_content_unit, pack_count, image_url, identity_key,
        created_at, updated_at
    ) values (
        p_name_ar, p_name_en, p_brand, p_variant,
        p_net_content_value, p_net_content_unit, greatest(coalesce(p_pack_count, 1), 1),
        p_image_url, v_identity_key, now(), now()
    )
    on conflict (identity_key) do update
    set canonical_name_ar = coalesce(public.canonical_products.canonical_name_ar, excluded.canonical_name_ar),
        canonical_name_en = coalesce(public.canonical_products.canonical_name_en, excluded.canonical_name_en),
        brand = coalesce(public.canonical_products.brand, excluded.brand),
        variant = coalesce(public.canonical_products.variant, excluded.variant),
        net_content_value = coalesce(public.canonical_products.net_content_value, excluded.net_content_value),
        net_content_unit = coalesce(public.canonical_products.net_content_unit, excluded.net_content_unit),
        pack_count = greatest(public.canonical_products.pack_count, excluded.pack_count),
        image_url = coalesce(public.canonical_products.image_url, excluded.image_url),
        updated_at = now()
    returning id into v_canonical_id;

    if p_source_url is not null then
        insert into public.retailer_identity_sources (
            canonical_product_id, retailer_id, identity_key, source_url, branch_key,
            active, last_checked_at, last_error
        ) values (
            v_canonical_id, v_retailer_id, v_identity_key, p_source_url,
            coalesce(nullif(p_branch_key, ''), 'online'), true, p_observed_at, null
        )
        on conflict (retailer_id, source_url) do update
        set canonical_product_id = excluded.canonical_product_id,
            identity_key = excluded.identity_key,
            branch_key = excluded.branch_key,
            active = true,
            last_checked_at = excluded.last_checked_at,
            last_error = null;
    end if;

    select * into v_current
    from public.identity_price_periods
    where canonical_product_id = v_canonical_id
      and retailer_id = v_retailer_id
      and branch_key = coalesce(nullif(p_branch_key, ''), 'online')
      and valid_to is null
    for update;

    if found
       and v_current.price = p_price
       and v_current.currency = coalesce(nullif(p_currency, ''), 'SAR') then
        update public.identity_price_periods
        set last_seen_at = p_observed_at,
            source_url = coalesce(p_source_url, source_url)
        where id = v_current.id;
        return v_canonical_id;
    end if;

    if found then
        update public.identity_price_periods
        set valid_to = p_observed_at,
            last_seen_at = greatest(last_seen_at, p_observed_at)
        where id = v_current.id;
    end if;

    insert into public.identity_price_periods (
        canonical_product_id, retailer_id, branch_key, price, currency,
        source_url, valid_from, valid_to, last_seen_at
    ) values (
        v_canonical_id, v_retailer_id, coalesce(nullif(p_branch_key, ''), 'online'),
        p_price, coalesce(nullif(p_currency, ''), 'SAR'), p_source_url,
        p_observed_at, null, p_observed_at
    );

    return v_canonical_id;
end;
$$;

revoke all on function public.record_identity_price(
    text, text, text, text, text, numeric, text, integer, text,
    text, text, numeric, text, text, timestamptz
) from public, anon, authenticated;
grant execute on function public.record_identity_price(
    text, text, text, text, text, numeric, text, integer, text,
    text, text, numeric, text, text, timestamptz
) to service_role;
