-- Saudi Master Barcode identity layer.
-- Supabase remains a hot cache; the full progressive corpus is stored as compressed GitHub Release shards.

create table if not exists public.saudi_barcode_evidence (
    id bigint generated by default as identity primary key,
    barcode text not null references public.products(barcode) on delete cascade,
    source text not null,
    source_tier text not null check (source_tier in ('official_saudi','open_global','retail_evidence')),
    source_record_id text not null,
    source_url text,
    confidence double precision not null check (confidence >= 0 and confidence <= 1),
    saudi_signal text not null,
    payload jsonb not null default '{}'::jsonb,
    first_seen_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    verified_at timestamptz,
    constraint saudi_barcode_evidence_source_record_unique unique (barcode, source, source_record_id)
);

create table if not exists public.saudi_product_presence (
    barcode text primary key references public.products(barcode) on delete cascade,
    canonical_product_id bigint references public.canonical_products(id) on delete set null,
    saudi_confidence double precision not null default 0.0 check (saudi_confidence >= 0 and saudi_confidence <= 1),
    best_source text not null,
    best_tier text not null check (best_tier in ('official_saudi','open_global','retail_evidence')),
    source_count integer not null default 1 check (source_count >= 1),
    saudi_signals text[] not null default '{}'::text[],
    first_seen_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    last_verified_at timestamptz,
    metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.saudi_master_sync_state (
    source text primary key,
    cursor bigint not null default 1 check (cursor >= 0),
    status text not null default 'idle',
    last_attempt_at timestamptz,
    last_success_at timestamptz,
    items_seen bigint not null default 0,
    items_imported bigint not null default 0,
    last_error text,
    metadata jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now()
);

create index if not exists idx_saudi_evidence_barcode
    on public.saudi_barcode_evidence(barcode);
create index if not exists idx_saudi_evidence_source
    on public.saudi_barcode_evidence(source, last_seen_at desc);
create index if not exists idx_saudi_presence_canonical
    on public.saudi_product_presence(canonical_product_id);
create index if not exists idx_saudi_presence_confidence
    on public.saudi_product_presence(saudi_confidence desc);
create index if not exists idx_saudi_presence_last_seen
    on public.saudi_product_presence(last_seen_at desc);

alter table public.saudi_barcode_evidence enable row level security;
alter table public.saudi_product_presence enable row level security;
alter table public.saudi_master_sync_state enable row level security;

-- No public policies by design. Only server-side/service-role ingestion may mutate or inspect these tables.
revoke all on table public.saudi_barcode_evidence from anon, authenticated;
revoke all on table public.saudi_product_presence from anon, authenticated;
revoke all on table public.saudi_master_sync_state from anon, authenticated;

create or replace function public.record_saudi_barcode_evidence(
    p_barcode text,
    p_canonical_product_id bigint,
    p_source text,
    p_source_tier text,
    p_source_record_id text,
    p_source_url text,
    p_confidence double precision,
    p_saudi_signal text,
    p_payload jsonb default '{}'::jsonb
) returns void
language plpgsql
set search_path to 'public'
as $$
declare
    v_count integer;
    v_signals text[];
    v_best record;
begin
    if p_barcode !~ '^[0-9]{8,14}$' then
        raise exception 'Invalid barcode: %', p_barcode;
    end if;
    if p_source_tier not in ('official_saudi','open_global','retail_evidence') then
        raise exception 'Invalid source tier: %', p_source_tier;
    end if;
    if p_source_record_id is null or btrim(p_source_record_id) = '' then
        raise exception 'source_record_id is required';
    end if;

    insert into public.saudi_barcode_evidence (
        barcode, source, source_tier, source_record_id, source_url,
        confidence, saudi_signal, payload, first_seen_at, last_seen_at, verified_at
    ) values (
        p_barcode, p_source, p_source_tier, p_source_record_id, p_source_url,
        greatest(0.0, least(coalesce(p_confidence,0),1.0)), p_saudi_signal,
        coalesce(p_payload,'{}'::jsonb), now(), now(),
        case when p_source_tier='official_saudi' then now() else null end
    )
    on conflict (barcode, source, source_record_id) do update
    set source_tier = excluded.source_tier,
        source_url = coalesce(excluded.source_url, public.saudi_barcode_evidence.source_url),
        confidence = greatest(public.saudi_barcode_evidence.confidence, excluded.confidence),
        saudi_signal = excluded.saudi_signal,
        payload = case
            when excluded.payload='{}'::jsonb then public.saudi_barcode_evidence.payload
            else excluded.payload
        end,
        last_seen_at = now(),
        verified_at = coalesce(excluded.verified_at, public.saudi_barcode_evidence.verified_at);

    select count(*)::int,
           array_agg(distinct saudi_signal order by saudi_signal)
      into v_count, v_signals
    from public.saudi_barcode_evidence
    where barcode=p_barcode;

    select source, source_tier, confidence
      into v_best
    from public.saudi_barcode_evidence
    where barcode=p_barcode
    order by
      case source_tier when 'official_saudi' then 3 when 'retail_evidence' then 2 else 1 end desc,
      confidence desc,
      last_seen_at desc
    limit 1;

    insert into public.saudi_product_presence (
        barcode, canonical_product_id, saudi_confidence, best_source, best_tier,
        source_count, saudi_signals, first_seen_at, last_seen_at, last_verified_at
    ) values (
        p_barcode, p_canonical_product_id, v_best.confidence, v_best.source, v_best.source_tier,
        greatest(v_count,1), coalesce(v_signals,'{}'::text[]), now(), now(),
        case when v_best.source_tier='official_saudi' then now() else null end
    )
    on conflict (barcode) do update
    set canonical_product_id=coalesce(excluded.canonical_product_id, public.saudi_product_presence.canonical_product_id),
        saudi_confidence=greatest(public.saudi_product_presence.saudi_confidence, excluded.saudi_confidence),
        best_source=excluded.best_source,
        best_tier=excluded.best_tier,
        source_count=excluded.source_count,
        saudi_signals=excluded.saudi_signals,
        last_seen_at=now(),
        last_verified_at=coalesce(excluded.last_verified_at, public.saudi_product_presence.last_verified_at);
end;
$$;

create or replace function public.refresh_saudi_master_snapshot(p_barcode text)
returns void
language plpgsql
set search_path to 'public'
as $$
declare
    v_existing jsonb := '{}'::jsonb;
    v_metadata jsonb;
    v_payload jsonb;
    v_canonical_id bigint;
    v_presence public.saudi_product_presence%rowtype;
    v_names record;
    v_aliases jsonb := '[]'::jsonb;
    v_existing_conf double precision := 0;
    v_existing_sources integer := 0;
begin
    select pa.canonical_product_id into v_canonical_id
    from public.product_aliases pa where pa.barcode=p_barcode;
    if v_canonical_id is null then return; end if;

    select * into v_presence from public.saudi_product_presence where barcode=p_barcode;
    if not found then return; end if;

    select coalesce(cp.canonical_name_ar,p.name_ar) as name_ar,
           coalesce(cp.canonical_name_en,p.name_en) as name_en,
           coalesce(cp.image_url,p.image_url) as image_url,
           cp.product_info
      into v_names
    from public.products p
    join public.canonical_products cp on cp.id=v_canonical_id
    where p.barcode=p_barcode;

    select coalesce(jsonb_agg(pa.barcode order by pa.barcode),'[]'::jsonb)
      into v_aliases
    from public.product_aliases pa where pa.canonical_product_id=v_canonical_id;

    select payload into v_existing from public.product_snapshots where barcode=p_barcode;
    v_existing := coalesce(v_existing,'{}'::jsonb);
    begin v_existing_conf := coalesce((v_existing->>'confidence')::double precision,0); exception when others then v_existing_conf:=0; end;
    begin v_existing_sources := coalesce((v_existing->>'source_count')::integer,0); exception when others then v_existing_sources:=0; end;

    v_metadata := jsonb_strip_nulls(jsonb_build_object(
        'barcode', p_barcode,
        'canonical_product_id', v_canonical_id,
        'matched_barcodes', v_aliases,
        'name_ar', v_names.name_ar,
        'name_en', v_names.name_en,
        'image_url', v_names.image_url,
        'source_count', greatest(v_existing_sources,v_presence.source_count),
        'confidence', greatest(v_existing_conf,v_presence.saudi_confidence),
        'product_info', v_names.product_info
    ));

    if not (v_existing ? 'current_price') or v_existing->'current_price'='null'::jsonb then
        v_metadata := v_metadata || jsonb_build_object(
            'exact_barcode_match', true,
            'headline_match_method', 'saudi_master_exact_gtin',
            'offers', coalesce(v_existing->'offers','[]'::jsonb),
            'currency', coalesce(v_existing->'currency','"SAR"'::jsonb)
        );
    end if;

    v_payload := v_existing || v_metadata;
    insert into public.product_snapshots(barcode,payload,payload_hash,updated_at)
    values(p_barcode,v_payload,md5(v_payload::text),now())
    on conflict(barcode) do update
    set payload=excluded.payload,payload_hash=excluded.payload_hash,updated_at=excluded.updated_at
    where public.product_snapshots.payload_hash is distinct from excluded.payload_hash;
end;
$$;

create or replace function public.ingest_saudi_master_batch(
    p_source text,
    p_source_tier text,
    p_saudi_signal text,
    p_rows jsonb
) returns jsonb
language plpgsql
set search_path to 'public'
as $$
declare
    v_row jsonb;
    v_barcode text;
    v_canonical_id bigint;
    v_imported integer := 0;
    v_rejected integer := 0;
    v_errors integer := 0;
begin
    if p_source_tier not in ('official_saudi','open_global','retail_evidence') then
        raise exception 'Invalid source tier: %', p_source_tier;
    end if;
    if jsonb_typeof(p_rows) <> 'array' then
        raise exception 'p_rows must be a JSON array';
    end if;

    for v_row in select value from jsonb_array_elements(p_rows)
    loop
        begin
            v_barcode := regexp_replace(coalesce(v_row->>'barcode',''), '\D', '', 'g');
            if v_barcode !~ '^[0-9]{8,14}$' then
                v_rejected := v_rejected + 1;
                continue;
            end if;

            v_canonical_id := public.upsert_product_metadata(
                p_barcode => v_barcode,
                p_name_ar => nullif(v_row->>'name_ar',''),
                p_name_en => nullif(v_row->>'name_en',''),
                p_brand => nullif(v_row->>'brand',''),
                p_image_url => nullif(v_row->>'image_url',''),
                p_gs1_verified => false,
                p_identity_key => null,
                p_variant => null,
                p_net_content_value => null,
                p_net_content_unit => null,
                p_pack_count => 1,
                p_match_confidence => coalesce((v_row->>'confidence')::double precision, 0.8),
                p_match_method => case when p_source_tier='official_saudi' then 'saudi_official_exact_gtin' else 'open_source_exact_gtin' end
            );

            if coalesce(v_row->'product_info','{}'::jsonb) <> '{}'::jsonb then
                perform public.upsert_product_info(v_barcode, v_row->'product_info');
            end if;

            perform public.record_saudi_barcode_evidence(
                v_barcode,
                v_canonical_id,
                p_source,
                p_source_tier,
                coalesce(nullif(v_row->>'source_record_id',''), v_barcode),
                nullif(v_row->>'source_url',''),
                coalesce((v_row->>'confidence')::double precision, 0.8),
                p_saudi_signal,
                coalesce(v_row->'evidence_payload','{}'::jsonb)
            );

            perform public.refresh_saudi_master_snapshot(v_barcode);
            v_imported := v_imported + 1;
        exception when others then
            v_errors := v_errors + 1;
        end;
    end loop;

    return jsonb_build_object('seen',jsonb_array_length(p_rows),'imported',v_imported,'rejected',v_rejected,'errors',v_errors);
end;
$$;

revoke execute on function public.record_saudi_barcode_evidence(text,bigint,text,text,text,text,double precision,text,jsonb) from public, anon, authenticated;
revoke execute on function public.refresh_saudi_master_snapshot(text) from public, anon, authenticated;
revoke execute on function public.ingest_saudi_master_batch(text,text,text,jsonb) from public, anon, authenticated;
grant execute on function public.record_saudi_barcode_evidence(text,bigint,text,text,text,text,double precision,text,jsonb) to service_role;
grant execute on function public.refresh_saudi_master_snapshot(text) to service_role;
grant execute on function public.ingest_saudi_master_batch(text,text,text,jsonb) to service_role;

insert into public.saudi_master_sync_state(source,cursor,status)
values
    ('sfda_food',0,'idle'),
    ('sfda_cosmetics',0,'idle'),
    ('open_food_facts_saudi',1,'idle'),
    ('open_products_facts_saudi',1,'idle'),
    ('open_beauty_facts_saudi',1,'idle'),
    ('open_pet_food_facts_saudi',1,'idle')
on conflict(source) do nothing;
